import { Injectable } from '@angular/core';
import { StudyArea } from '@wildcat/interfaces';

@Injectable({
	providedIn: 'root',
})
export class StudyAreaService {
	regions: String[] = [
		'Aragón',
		'Castilla La Mancha',
		'Castilla y León',
		'Extremadura',
		'Región de Murcia',
	];

	studyAreas: StudyArea[] = [
		{
			contact: 'antorrijo@yahoo.es',
			coords: [40.920251, -1.371063],
			link: 'https://drive.google.com/open?id=1Y2xcyr-cTZWQiorBA_u0Jkf4ZxPmxmSM, https://drive.google.com/open?id=1rWyLpMyN2mGkm1t8k15D9IMG4fIo2VVB, https://drive.google.com/open?id=1VR3ZZY-1aWIhr2PwZ-iIc1NkI_06kVZB, https://drive.google.com/open?id=15bkHquuqRkkFrP8oqJcq4cgi5oq6y8uj, https://drive.google.com/open?id=1ehxVDhvMGNliz3R5JqHI5D8KvBGBJthU, https://drive.google.com/open?id=13A3orZt1emCCtusPef8KvRt-cVevtzxG, https://drive.google.com/open?id=1LIZP6ehO_hwmhCFqgwqvtuA-Ayw5PIkW, https://drive.google.com/open?id=1xs5lAfJIeagz2XIk8Uz3eUdNYGPn2hQU, https://drive.google.com/open?id=1afjT7pB0CVzlBUm_LefPJk11xneKxPol, https://drive.google.com/open?id=1GV86owr1xGCr_N9z9kBSzpIMLN9Xxsu6',
			months: 'Febrero y Marzo',
			partners: [
				'José Miguel Pueyo Soler',
				'Luis Miguel Bautista Sopelana',
				'Tomas Jordán Gargallo',
			],
			presence: true,
			province: 'Teruel',
			region: 'Aragón',
			year: '2023',
			leader: 'Antonio Torrijo Pardos',
			name: 'Valdellosa',
			leaderEmail: 'antorrijo@yahoo.es',
		},
		{
			contact: 'antorrijo@yahoo.es',
			coords: [41.152939, -1.098953],
			link: 'https://drive.google.com/open?id=1RN9-vFWBITBHAOtjEOH8iDVCYIqIgn85, https://drive.google.com/open?id=16GrneyFhfFSt7CAAcI-0FPjxVgcRb-NY, https://drive.google.com/open?id=1MYl14wU6b_sfAa0yuM7wmNPcW6QgkbTQ, https://drive.google.com/open?id=1V9zIUBggaaq59waTBlv4NNumjoEf_J8P, https://drive.google.com/open?id=1mp2U06kGVsNqu3P-rcnJl40cQXzhRRbN, https://drive.google.com/open?id=1AeiLcyDSTSc4RR7XoEVWsDwhKQyGORTL, https://drive.google.com/open?id=1Ig_ylN20HKC5BkjVVmitrezX0zqmTXvJ, https://drive.google.com/open?id=18BJUTR0K_-sR4YaGAiQUIbFsFGm1thb8, https://drive.google.com/open?id=1rah29Xe3gUki_cwxCSullOzla_hHWi5G, https://drive.google.com/open?id=1cPK4miSIw9xf9gW3oNddjatFSk0barIz',
			months: 'Mayo, Junio y Julio',
			partners: ['José Miguel Pueyo Soler'],
			presence: true,
			province: 'Teruel',
			region: 'Aragon',
			year: '2024',
			leader: 'Antonio Torrijo Pardos',
			name: 'rio Camaras',
			otherName: 'Sierra de Herrera/Nogueras',
			leaderEmail: 'antorrijo@yahoo.es',
		},
		{
			contact: 'albertofaunaran@gmail.com',
			coords: [42.841238, 0.689718],
			link: 'https://drive.google.com/open?id=1KCA3UtEjEcZq60ca9NDbuEfs5490F8vC, https://drive.google.com/open?id=1X5rgjuGdC0RF-ryEyw-EuDAt6ffoExrZ, https://drive.google.com/open?id=1cpF56BrO4S0g3bw9Me_HccmwsSTdNwq6, https://drive.google.com/open?id=1Q_2rkhuMcii64LUYJEqmYnC_mUwP0ARo, https://drive.google.com/open?id=1eBqqR7fjNQC2ivRdSlNJ-6rpIOXAYls6',
			months: 'Julio, agosto, septiembre',
			partners: [
				'Alberto Ginés',
				'Sara Barba',
				'Pau Ortiz',
				'Gemma Rey',
				'Javi Gil',
				'Carolina Gonzalez',
				'Eva sanchez',
				'Sandra ripoll',
				'Sara cabañas',
			],
			presence: true,
			province: 'Lleida',
			region: 'Catalunya',
			year: '2024',
			leader: 'Aran pera natura',
			name: "VAG (Val d'aran gat)",
			leaderEmail: 'albertofaunaran@gmail.com',
		},
		{
			contact: 'tiracantos@gmail.com',
			coords: [42.51945, -4.327294],
			link: 'https://drive.google.com/open?id=1ePbOTqJWwxOjE88caUJNDEYPxqQgRcKx, https://drive.google.com/open?id=1Gc17kOdWPeKOYQvJoXza7O9P5HlHKnUl, https://drive.google.com/open?id=14jcbob37Kx2aC63xVtGkSxPr5wqw_vMr, https://drive.google.com/open?id=1ab-mccdW-MC44WQgyGIMJnnkttCbjtfr, https://drive.google.com/open?id=1WY4hWxeHwTaS9g0pifoiZbZvu4cRo-X3, https://drive.google.com/open?id=15V2TSFsStUWjcg0NCjBlp58i2aVefUre, https://drive.google.com/open?id=10_aHCnTxLxqCQIg8RTfOjBSWsclbp6Xl, https://drive.google.com/open?id=1CXlTVEvIOex2cm5w0muzTR2PODX_oer5, https://drive.google.com/open?id=1EoyDE0EeJXlQZ4ryMiCn08m8z0KWKlRW',
			months: 'Mayo a Julio',
			partners: ['César María Aguilar Gómez', 'Ricardo Zaldívar López'],
			presence: true,
			province: 'Logroño',
			region: 'La Rioja',
			year: '2023',
			leader: 'César María Aguilar Gómez',
			name: 'PIEDEMONTE-VENTOSA_LR',
			leaderEmail: 'tiracantos@gmail.com',
		},
		{
			contact: 'saliegosbirding@gmail.com',
			coords: [41.605488, -6.02624],
			months: 'My-Ag',
			partners: ['Cristian Osorio Huerga', 'José Alfredo Hernández Rodríguez'],
			presence: false,
			province: 'Zamora',
			region: 'Castilla y León',
			year: '2023',
			leader: 'Cristian Osorio Huerga',
			name: 'Zamora. Entorno al alcornocal de Cerezal de Aliste. /Ricobayo',
			leaderEmail: 'saliegosbirding@gmail.com',
		},
		{
			contact: 'emiliogmiras@serbal-almeria.org',
			coords: [37.112223, -1.897857],
			months: 'julio-agosto',
			partners: ['Emilio González Miras'],
			presence: true,
			province: 'Almería',
			region: 'Andalucia',
			year: '2022',
			leader: 'Emilio Gonzalez Miras',
			name: 'ZEC Sierra Cabrera-Bedar',
			otherName: 'Cabo de Gata-Cabrera',
			leaderEmail: 'emiliogmiras@serbal-almeria.org',
		},
		{
			contact: 'emiliogmiras@serbal-almeria.org',
			coords: [36.8432, -2.722902],
			months: 'abril-julio',
			partners: ['Emilio González Miras'],
			presence: true,
			province: 'Almería',
			region: 'Andalucia',
			year: '2022',
			leader: 'Emilio González Miras',
			name: 'Sierra de Gádor (Almería)',
			leaderEmail: 'emiliogmiras@serbal-almeria.org',
		},
		{
			contact: 'emiliogmiras@serbal-almeria.org',
			coords: [37.264543, -2.520795],
			months: 'agosto-septiembre',
			partners: [
				'Emilio González Miras',
				'Miguel Aguadero',
				'Mauricio Santa Trejos',
				'Jose Luis Molina',
				'Francisco Silva',
				'Francisco Sanchez Camacho',
			],
			presence: true,
			province: 'Almería',
			region: 'Andalucía',
			year: '2019',
			leader: 'Emilio González Miras',
			name: 'Sierra de los Filabres',
			leaderEmail: 'emiliogmiras@serbal-almeria.org',
		},
		{
			contact: 'emiliogmiras@serbal-almeria.org',
			coords: [37.076831, -2.561214],
			months: 'octubre-noviembre',
			partners: ['Emilio González Miras'],
			presence: false,
			province: 'Almería',
			region: 'Andalucía',
			year: '2019',
			leader: 'Emilio González Miras',
			name: 'Desierto de Tabernas',
			leaderEmail: 'emiliogmiras@serbal-almeria.org',
		},
		{
			contact: 'elarreta@gmail.com',
			coords: [42.521662, -4.327356],
			months: 'Marzo a julio',
			partners: ['Enrique Fernández Larreta-Azelain'],
			presence: true,
			province: 'Palencia',
			region: 'Castilla y León',
			year: '2023',
			leader: 'Enrique Fernández Larreta-Azelain',
			name: 'Montaña palentina',
			otherName: 'Ventosa del Pisuerga?',
			leaderEmail: 'elarreta@gmail.com',
		},
		{
			contact: 'evarubiolopez@hotmail.es',
			coords: [42.380707, -1.105877],
			link: 'https://drive.google.com/open?id=1MucT1qET_4lcH8eeoRKQLyGgot0cZAkD, https://drive.google.com/open?id=1Au9VgPdZ_teOd--ZE9hsQ2-olQpoapzI, https://drive.google.com/open?id=1GOv5Z4NNkSKKZsYV_nhRWpFnYQNKgxXt, https://drive.google.com/open?id=1_vg3qOZFxxl92Rya2Ira_ht_u26IaOtP, https://drive.google.com/open?id=1-C1N9i0fM_Rqkwo3sGj4W0GawCCPVhla',
			months: 'Marzo y abril',
			partners: ['Eva Carmen Rubio López'],
			presence: true,
			province: 'Zaragoza',
			region: 'Aragón',
			year: '2024',
			leader: 'Eva Carmen Rubio López',
			name: 'Uncastillo',
			leaderEmail: 'evarubiolopez@hotmail.es',
		},
		{
			contact: 'pacobustamantec@gmail.com',
			coords: [40.378331, -3.22888],
			months: 'Febrero, marzo, abril, mayo',
			partners: [
				'Francisco Bustamante Collado',
				'Toñi Rodríguez Caballero',
				'Cristóbal Jurado Ales',
				'Eduardo Romero Fernández',
				'Helena García Bayón\nIván Salgado García\nJavier Gutiérrez Huete',
			],
			presence: true,
			province: 'Madrid',
			region: 'Comunidad de Madrid',
			year: '2024',
			leader: 'Francisco Bustamante Collado',
			name: 'Nuevo Baztan -Alcarria de Madrid',
			leaderEmail: 'pacobustamantec@gmail.com',
		},
		{
			contact: 'javher80@gmailc.om',
			coords: [38.674031, -3.190624],
			months: 'Julio-Agosto-Septiembre',
			partners: ['Agentes Medioambientales (Comarca de Infantes)'],
			presence: true,
			province: 'Ciudad Real',
			region: 'Castilla la Mancha',
			year: '2022',
			leader: 'Francisco Javier Herrera Sanchez',
			name: 'Embalse la cabezuela',
			leaderEmail: 'javher80@gmailc.om',
		},
		{
			contact: 'javher80@gmail.com',
			coords: [38.675638, -2.829774],
			months: 'Julio-Agosto-Septiembre',
			partners: ['Agentes Medioambientales (Comarca de Infantes)'],
			presence: true,
			province: 'Ciudad Real',
			region: 'Castilla La Mancha',
			year: '2022',
			leader: 'Francisco Javier Herrera Sanchez',
			name: 'Albadalejo',
			leaderEmail: 'javher80@gmail.com',
		},
		{
			contact: 'lberenguerg@gmail.com',
			coords: [40.553909, -3.837938],
			link: 'https://drive.google.com/open?id=1Zj8bFVu4elPUO95OAHbWtvhzAx4sTQSF, https://drive.google.com/open?id=14SVkvu-Au4kaDyL7CU5HGorbuzC3CvKd, https://drive.google.com/open?id=1RSG9A8bA6OicPt-GzskwLmw5LZLDnQuu, https://drive.google.com/open?id=1X0MuXI0OViUfqYH0WHoTjpIHVAEiBcvS, https://drive.google.com/open?id=1mBeFxe5at2rFbwcZ7MkPvXAWrxBAQfsP, https://drive.google.com/open?id=1_Hq1pwp3F7OB3G8BglGAyaIN8X7ii3Oi, https://drive.google.com/open?id=1MnVf0JS-S2nHOEb9dAS-8mr7PTbHuhI8, https://drive.google.com/open?id=1PpiNYSPY3D2i73RR2OF9q8XtxbhTUZ36, https://drive.google.com/open?id=1ZuWU6aZ-khqHR4O1dS-EKsCb3-tnw1tF',
			months: 'Octubre, noviembre, diciembre y enero',
			partners: [
				'Alberto Díez Herrero',
				'Alicia Martínez Higuera',
				'Carolina García García',
				'Lara Berenguer Gutiérrez',
			],
			presence: false,
			province: 'Madrid',
			region: 'Madrid',
			year: '2024-2025',
			leader: 'Guadarrama Río de arena',
			name: 'PR Río Guadarrama',
			leaderEmail: 'lberenguerg@gmail.com',
		},
		{
			contact: 'guillecarmonacastresana@gmail.com',
			coords: [41.471135, -4.358193],
			months: 'Noviembre - diciembre',
			partners: ['Guillermo Carmona Castresana'],
			presence: true,
			province: 'Valladolid',
			region: 'Castilla y León',
			year: '2021',
			leader: 'Guillermo Carmona Castresana',
			name: 'Aldealbar',
			leaderEmail: 'guillecarmonacastresana@gmail.com',
		},
		{
			contact: 'guillecarmonacastresana@gmail.com',
			coords: [41.849617, -4.182623],
			months: 'Noviembre - diciembre',
			partners: ['Guillermo Carmona Castresana'],
			presence: true,
			province: 'Palencia',
			region: 'Castilla y León',
			year: '2021',
			leader: 'Guillermo Carmona Castresana',
			name: 'Cevico Navero',
			leaderEmail: 'guillecarmonacastresana@gmail.com',
		},
		{
			contact: 'chinhector@gmail.com',
			coords: [42.931609, -6.387837],
			link: 'https://drive.google.com/open?id=1Y41Y3sbPJ-RgK4HkpqfW9DlOW0tbq3eO, https://drive.google.com/open?id=1RNN018y13DCeyXVenFt1tAecVpFy-kiD, https://drive.google.com/open?id=1aGlK-XQeHgv_znd221U9BMWxzmsVgyfr, https://drive.google.com/open?id=1whm2ipn61_kP0fLQJtlkSaxWBYzFe6Na, https://drive.google.com/open?id=1lJAB2l1nnUstjkIO_CE1I7xA9sVI1ifs, https://drive.google.com/open?id=1O7cvmBrAHzu4BbM0XAYa0nSWV6i5jJj1, https://drive.google.com/open?id=1h84R_fQiuH9pHIj6dOtC_7HPix4c105z, https://drive.google.com/open?id=1OVRyEY-MDcOtqcA7GuUNMuVrYp0gX09c, https://drive.google.com/open?id=1nuXdpyKyj11bFp1yjIdIRrua-AuVI32G, https://drive.google.com/open?id=19p6w4yXqFHFe5kQ3dWWAB1L8THwCrV5N',
			months: 'Marzo a Mayo',
			partners: [
				'Héctor Ruiz Villar',
				'Ana Morales González',
				'Ezequiel Martínez Vera',
				'Florentino Ruiz Barreiro',
			],
			presence: true,
			province: 'León',
			region: 'Castilla y León',
			year: '2021',
			leader: 'Héctor Ruiz Villar',
			name: 'Alto Sil leonés',
			otherName: 'Occidente Cordillera Cantábrica',
			leaderEmail: 'chinhector@gmail.com',
		},
		{
			contact: 'bermejonatur@hotmail.com',
			coords: [42.122781, 2.546384],
			months: 'Octubre/Noviembre//Diciembre',
			partners: ['Isidre Cos Arnau'],
			presence: true,
			province: 'Girona',
			region: 'Catalunya',
			year: '2019',
			leader: 'Jordi Bermejo Cabezas',
			name: 'Girona (Vall del Llémena)',
			leaderEmail: 'bermejonatur@hotmail.com',
		},
		{
			contact: 'josemiguel.aguilar11@gmail.com',
			coords: [39.991128, -0.552938],
			link: 'https://drive.google.com/open?id=1xUWmFWOL1CT0P4JhfjV3gQA4gLC-sIa6, https://drive.google.com/open?id=1UkqOV2linRfGtImWlt_d979LKy4i66L7, https://drive.google.com/open?id=1tg0odOmYZQnf3yYmBhp2enEFXzxRrB7u, https://drive.google.com/open?id=10zABXVAAeqgGxxTfty6tOSGj0BjQPhom, https://drive.google.com/open?id=17MDCNch57t-2zS0PQRUHHbl7UiDY_9nr, https://drive.google.com/open?id=1-rJ2zpFLwBlYYfpmdE6pEJaETCDSCIQ9, https://drive.google.com/open?id=1CSsAUpyr2KQ5EmadQ5_esym7-zzi-QPC, https://drive.google.com/open?id=1jvqI58l7sEilwSfXcYg6zLyoC7JJ-h-o, https://drive.google.com/open?id=18eK9RBt7hQZ0smNNzGoEJI13Yyoab799',
			months: 'julio 2023-octubre 2023',
			partners: [
				'Jose Miguel Aguilar Serrano\nSantiago Marco Gracia\nFrancisco Javier Lloris Martínez\nFrancisco García López\nJose Giménez Segarra',
			],
			presence: true,
			province: 'Castellón',
			region: 'Comunidad Valenciana',
			year: '2023',
			leader: 'Jose Miguel Aguilar Serrano',
			name: 'Sierra de Espadán NW (Sierra de Caudiel)',
			otherName: 'Sierra de Caudiel, Sierra de ESPADÁN NW',
			leaderEmail: 'josemiguel.aguilar11@gmail.com',
		},
		{
			contact: 'josemiguel.aguilar11@gmail.com',
			coords: [39.958775, -0.809982],
			link: 'https://drive.google.com/open?id=1-f25lpe414rVInwN19WvMmbhVPwRxU2B, https://drive.google.com/open?id=1VHZ7lLwfhPYah1JWsdjEqqIWrJqpDv13, https://drive.google.com/open?id=19XtzxectsT49hOZc6ljMJ2nkwp8OfDFk, https://drive.google.com/open?id=1qlT7u3UhXVUr1foSytFPdn4r5ggI6EAK, https://drive.google.com/open?id=1daWq0D_o426aA1LvyOJmlaBBr9oTA7JT, https://drive.google.com/open?id=1oti5X50RZxXD5nIqHUAIW5JRoqdCQ-fB, https://drive.google.com/open?id=1ZLZmdR_ItSiWalXNny9usBcLYjWUPMCG, https://drive.google.com/open?id=1heqsgD8-fbiaHZFyKcNXzSOtFuYhb6qH, https://drive.google.com/open?id=1PpL2qekN4Lp49a3Vzv-Fx29t2mOJXZla, https://drive.google.com/open?id=1Zjvt1DDjg7OX1BjeyBWfSO7jv0eU0qnE',
			months: 'diciembre 2024- marzo 2025',
			partners: [
				'Jose Miguel Aguilar Serrano\nSantiago Marco Gracia\nEusebio García Orduña\nManuel García Tarrasón\nFrancisco Javier Lloris Martínez',
			],
			presence: true,
			province: 'Castellón',
			region: 'Comunidad Valenciana',
			year: '2024',
			leader: 'Jose Miguel Aguilar Serrano',
			name: 'Sierra de El Toro',
			otherName: 'Sierra de El Toro, SW Sistema ibérico',
			leaderEmail: 'josemiguel.aguilar11@gmail.com',
		},
		{
			contact: 'eleusis38@hotmail.com',
			coords: [37.578635, -2.038166],
			months: 'Enero, febrero, marzo y abril',
			partners: [
				'Ana Belen Martinez Parra',
				'Gines Jesus Gomez Sanchez',
				'Blas Gonzalez Martinez',
				'Jose Miguel Gomez Sanchez',
			],
			presence: true,
			province: 'Almeria',
			region: 'Andalucia',
			year: '2021',
			leader: 'Jose Miguel Gomez Sanchez',
			name: 'Sierra Estancias (Almeria)',
			leaderEmail: 'eleusis38@hotmail.com',
		},
		{
			contact: 'juliancsoriano47@gmail.com',
			coords: [38.731319, -1.226226],
			link: 'https://drive.google.com/open?id=16mzrGxhkY4bY0KAImib0RBAhWVIFxKVn, https://drive.google.com/open?id=14FMyHaqc8pFhMJlFFjcM9l9uk_WSEAum, https://drive.google.com/open?id=1IkbJXYVzYifoAhdUNxGrlgqiZ4ApXBXc, https://drive.google.com/open?id=1sPbJQxfYCsjDWesg7sAqVDN4WCjZURdZ, https://drive.google.com/open?id=1RFIADhvVeKxivshjF6ERaPN_pCOlHWCK, https://drive.google.com/open?id=1JDQTOA3u1YkthkehJt-uBglrN9rlULz7, https://drive.google.com/open?id=1kOBPhrf7lg9d3u6Jz4jidP9a-T-uGy9f, https://drive.google.com/open?id=12rPEqAJ2iOR7CVwmvC7KN495JDFCvNpL, https://drive.google.com/open?id=14cafAUlbS2r1ugYt9qoAGswIkJiBVxXN, https://drive.google.com/open?id=1Aj1CH4kUaZym1yDL-UI3D0P5ypVC141F',
			months: 'Junio/Julio',
			partners: [
				'Julián Castaño Soriano (Asociación Naturalista para la Investigación y Defensa del Altiplano-ANIDA)',
			],
			presence: true,
			province: 'Murcia',
			region: 'Región de Murcia',
			year: '2024',
			leader: 'Julián Castaño Soriano',
			name: 'Monte Arabí - Yecla',
			leaderEmail: 'juliancsoriano47@gmail.com',
		},
		{
			contact: 'jmgdrosera@gmail.com',
			coords: [40.510273, -6.109444],
			months: 'Enero a abril',
			partners: ['Julián Martín Garde'],
			presence: false,
			province: 'Salamanca',
			region: 'Castilla y León',
			year: '2022',
			leader: 'Julián Martín Garde',
			name: 'Sierra de Francia',
			leaderEmail: 'jmgdrosera@gmail.com',
		},
		{
			contact: 'lope.lorenzo@gmail.com',
			coords: [38.154884, -2.350179],
			link: 'https://drive.google.com/open?id=1oRDgmFw45m6g-YKVDr29kKwXcylg-fKB, https://drive.google.com/open?id=1AEf3BF87TWN3pQ2yWGakjt8Lu1dStlFd, https://drive.google.com/open?id=1rlbB5sDPs89XQoybRrvc0K57fQO68gDh, https://drive.google.com/open?id=1g86N1oSNZ5wX88h49J6f6GXEk3cHQEhz, https://drive.google.com/open?id=1jMm4BU0xcncGclkhw6k8l_pUYjscbYVO',
			months: 'Mayo, junio, julio (retiradas: 4 julio)',
			partners: ['Trino Ferrández', 'Chema Catarineu', 'Lope Lorenzo'],
			presence: false,
			province: 'Albacete',
			region: 'Castilla-La Mancha',
			year: '2021',
			leader: 'Lope Lorenzo Martínez',
			name: 'Nerpio',
			leaderEmail: 'lope.lorenzo@gmail.com',
		},
		{
			contact: 'lorejaruco@gmail.com',
			coords: [40.4168, -3.7038],
			months: 'Abril-junio',
			partners: [
				'Loreto García Román',
				'Felipe Peñalosa García',
				'Félix Martínez Olivas',
				'Jorge Calero Ramírez',
			],
			presence: false,
			province: 'Madrid',
			region: 'Comunidad de Madrid',
			year: '2024',
			leader: 'Loreto García Román',
			name: 'Parque Regional del Sureste',
			leaderEmail: 'lorejaruco@gmail.com',
		},
		{
			contact: 'marc.vilella16@gmail.com',
			coords: [42.107995, 2.362039],
			link: 'https://drive.google.com/open?id=1fh9J14AKQqdrWfVqJfZGysMFNVqplF-s, https://drive.google.com/open?id=18ioXVyKuOFCS_ZpJ6-5tZbYLZ5NBBeWJ, https://drive.google.com/open?id=1-qnt8Y98I8lkqk3Zr5Z_FS53WSgw0Nzh, https://drive.google.com/open?id=1Lb_uCToJ6DFBT9KZyLLbwL6CCUXngcNi, https://drive.google.com/open?id=1uYXXYydFjdE_MgNh-GiR2QepcV9D5dsZ, https://drive.google.com/open?id=1GC6iQHzYA8dvVxmfw0PYPhOgsANVrZa_, https://drive.google.com/open?id=1iOaFrsPg1U3aWOc9M_7G4q9hGvkPrp53, https://drive.google.com/open?id=1GLmCDEyjMu52D_XuApcDK8V2EMiQIX9A, https://drive.google.com/open?id=1vQInhEoISUpSYRBMkL2iP2apWkSC546I, https://drive.google.com/open?id=1KDEX4KfZdb0zaLgiKKOVhADFmO4wAkAb',
			months: 'febrero, marzo, abril',
			partners: [
				'Ferran Sayol',
				'Eric Serratosa',
				'Marc Rota',
				'Xevi Arumí',
				'Alfred Encuentra',
				'Marc Vilella',
			],
			presence: true,
			province: 'Barcelona',
			region: 'Catalunya',
			year: '2021',
			leader: 'Marc Vilella Antonell',
			name: 'Sant Pere Torello (BCN)',
			leaderEmail: 'marc.vilella16@gmail.com',
		},
		{
			contact: 'juanodecinca@gmail.com',
			coords: [41.572451, -0.080716],
			months: 'Diciembre Enero Febrero',
			partners: ['Miguel Ángel Pena Ferrer'],
			presence: true,
			province: 'Huesca',
			region: 'Aragón',
			year: '2021-2022',
			leader: 'Miguel Ángel Pena Ferrer',
			name: 'Monegros',
			otherName: 'Sierra de Sigena',
			leaderEmail: 'juanodecinca@gmail.com',
		},
		{
			contact: 'pablomonroymartinez@gmail.com',
			coords: [41.518349, -1.736418],
			months: 'Junio, julio y agosto',
			partners: ['Pablo Monroy'],
			presence: true,
			province: 'Zaragoza',
			region: 'Aragón',
			year: '2020',
			leader: 'Pablo Monroy Martínez',
			name: 'Sierra de la Virgen',
			otherName: 'Zaragoza',
			leaderEmail: 'pablomonroymartinez@gmail.com',
		},
		{
			contact: 'Chavaldelapetra@gmail.com',
			coords: [40.839059, -1.70625],
			months: 'Abril mayo',
			partners: ['Uge Fuertes Sanz'],
			presence: true,
			province: 'Guadajara',
			region: 'Castilla la Mancha',
			year: '2024',
			leader: 'Uge Fuertes Sanz',
			name: 'Sierra caldereros',
			leaderEmail: 'Chavaldelapetra@gmail.com',
		},
		{
			contact: 'javierhh95@gmail.com',
			coords: [40.158403, -4.728151],
			months: 'Febrero-abril',
			partners: ['Javier Hernández', 'Emilio Virgós'],
			presence: true,
			province: 'Toledo',
			region: 'Castilla la Mancha',
			year: '2022',
			leader: 'Javier Hernández',
			name: 'Sª Gredos',
			otherName: 'Navamorcuende- El Real de San Vicente',
			leaderEmail: 'javierhh95@gmail.com',
		},
		{
			contact: 'javierhh95@gmail.com',
			coords: [40.724643, -2.345086],
			months: 'Enero-abril',
			partners: ['Javier Hernández', 'Emilio Virgós'],
			presence: true,
			province: 'Guadajara',
			region: 'Castilla la Mancha',
			year: '2022',
			leader: 'Javier Hernández',
			name: 'Alto tajo',
			otherName: 'Zaorejas',
			leaderEmail: 'javierhh95@gmail.com',
		},
		{
			contact: 'javierhh95@gmail.com',
			coords: [40.517663, -4.359074],
			months: 'Junio-agosto',
			partners: ['Javier Hernández', 'Emilio Virgós'],
			presence: false,
			province: 'Ávila',
			region: 'Castilla y León',
			year: '2021',
			leader: 'Javier Hernández',
			name: 'Hoyo de Pinares',
			leaderEmail: 'javierhh95@gmail.com',
		},
		{
			contact: 'javierhh95@gmail.com',
			coords: [42.954473, -1.471698],
			months: 'Junio-diciembre',
			partners: ['Javier Hernández'],
			presence: true,
			province: 'Navarra',
			region: 'Comunidad Foral de Navarra',
			year: '2022',
			leader: 'Javier Hernández',
			name: 'Erro',
			otherName: 'Zilbeti',
			leaderEmail: 'javierhh95@gmail.com',
		},
		{
			contact: 'javierhh95@gmail.com',
			coords: [41.552081, -2.576438],
			months: 'Febrero-abril',
			partners: ['Javier Hernández', 'Emilio Virgós'],
			presence: true,
			province: 'Soria',
			region: 'Castilla y León',
			year: '2022',
			leader: 'Javier Hernández',
			name: 'Almazán',
			otherName: 'Soria',
			leaderEmail: 'javierhh95@gmail.com',
		},
		{
			contact: 'javierhh95@gmail.com',
			coords: [40.96278, -3.503573],
			months: 'Febrero-abril',
			partners: ['Javier Hernández', 'Emilio Virgós'],
			presence: true,
			province: 'Madrid',
			region: 'Comunidad de Madrid',
			year: '2021',
			leader: 'Javier Hernández',
			name: 'Robledillo de la Jara',
			leaderEmail: 'javierhh95@gmail.com',
		},
		{
			contact: 'javierhh95@gmail.com',
			coords: [40.727144, -4.929763],
			months: 'Julio-noviembre',
			partners: ['Javier Hernández', 'Emilio Virgós'],
			presence: true,
			province: 'Ávila',
			region: 'Castilla y León',
			year: '2022',
			leader: 'Javier Hernández',
			name: 'Cillán',
			otherName: 'Ávila/Horcajuelo',
			leaderEmail: 'javierhh95@gmail.com',
		},
		{
			contact: 'javierhh95@gmail.com',
			coords: [40.105079, -2.509681],
			months: 'Mayo-julio',
			partners: ['Javier Hernández', 'Emilio Virgós'],
			presence: true,
			province: 'Cuenca',
			region: 'Castilla la Mancha',
			year: '2021',
			leader: 'Javier Hernández',
			name: 'Alto de cabreja',
			leaderEmail: 'javierhh95@gmail.com',
		},
		{
			contact: 'javierhh95@gmail.com',
			coords: [40.24151, -3.228976],
			months: 'Noviembre-enero',
			partners: ['Javier Hernández', 'Tamara Burgos', 'Emilio Virgós'],
			presence: true,
			province: 'Madrid',
			region: 'Comunidad de Madrid',
			year: '2020-2021',
			leader: 'Javier Hernández',
			name: 'Carabaña',
			leaderEmail: 'javierhh95@gmail.com',
		},
		{
			contact: 'javbarona@gmail.com',
			coords: [39.404687, -1.223058],
			months: 'Febrero-junio',
			partners: ['Javier Barona', 'María Jesús Sanchís'],
			presence: true,
			province: 'Valencia',
			region: 'Comunidad Valenciana',
			year: '2020',
			leader: 'Javier Barona',
			name: 'Albosa',
			leaderEmail: 'javbarona@gmail.com',
		},
		{
			contact: 'javbarona@gmail.com',
			coords: [38.823724, -0.823898],
			months: 'Marzo-mayo',
			partners: ['Javier Barona', 'María Jesús Sanchís'],
			presence: true,
			province: 'Alicante',
			region: 'Comunidad Valenciana',
			year: '2024',
			leader: 'Javier Barona',
			name: 'Moixent',
			leaderEmail: 'javbarona@gmail.com',
		},
		{
			contact: 'javbarona@gmail.com',
			coords: [38.63617, -0.329426],
			months: 'Junio-julio',
			partners: ['Javier Barona', 'María Jesús Sanchís'],
			presence: true,
			province: 'Alicante',
			region: 'Comunidad Valenciana',
			year: '2022',
			leader: 'Javier Barona',
			name: 'Aitana',
			leaderEmail: 'javbarona@gmail.com',
		},
		{
			contact: 'javbarona@gmail.com',
			coords: [38.586843, -0.740331],
			months: 'Octubre-diciembre',
			partners: ['Javier Barona', 'María Jesús Sanchís'],
			presence: true,
			province: 'Alicante',
			region: 'Comunidad Valenciana',
			year: '2020',
			leader: 'Javier Barona',
			name: 'Castalla Arguenya',
			leaderEmail: 'javbarona@gmail.com',
		},
		{
			contact: 'javbarona@gmail.com',
			coords: [38.674627, -0.575566],
			months: 'Julio-septiembre',
			partners: ['Javier Barona', 'María Jesús Sanchís'],
			presence: false,
			province: 'Alicante',
			region: 'Comunidad Valenciana',
			year: '2022',
			leader: 'Javier Barona',
			name: 'Font Roja',
			leaderEmail: 'javbarona@gmail.com',
		},
		{
			contact: 'javbarona@gmail.com',
			coords: [38.994191, -0.394738],
			months: 'Octubre-diciembre',
			partners: ['Javier Barona', 'María Jesús Sanchís'],
			presence: true,
			province: 'Valencia',
			region: 'Comunidad Valenciana',
			year: '2023',
			leader: 'Javier Barona',
			name: 'Barx',
			leaderEmail: 'javbarona@gmail.com',
		},
		{
			contact: 'javbarona@gmail.com',
			coords: [38.781966, -0.375583],
			months: 'Abril-junio',
			partners: ['Javier Barona', 'María Jesús Sanchís'],
			presence: true,
			province: 'Alicante',
			region: 'Comunidad Valenciana',
			year: '2023',
			leader: 'Javier Barona',
			name: 'Beniarrés',
			leaderEmail: 'javbarona@gmail.com',
		},
		{
			contact: 'javbarona@gmail.com',
			coords: [38.547347, -0.444166],
			months: 'Marzo-junio',
			partners: ['Javier Barona', 'María Jesús Sanchís'],
			presence: false,
			province: 'Alicante',
			region: 'Comunidad Valenciana',
			year: '2024',
			leader: 'Javier Barona',
			name: 'Cabeso DOr',
			leaderEmail: 'javbarona@gmail.com',
		},
		{
			contact: 'javbarona@gmail.com',
			coords: [38.276542, -0.862306],
			months: 'Enero-febrero',
			partners: ['Javier Barona', 'María Jesús Sanchís'],
			presence: false,
			province: 'Alicante',
			region: 'Comunidad Valenciana',
			year: '2024',
			leader: 'Javier Barona',
			name: 'Crevillente',
			leaderEmail: 'javbarona@gmail.com',
		},
		{
			contact: 'javbarona@gmail.com',
			coords: [37.93321, -0.861585],
			months: 'Septiembre-noviembre',
			partners: ['Javier Barona', 'María Jesús Sanchís'],
			presence: true,
			province: 'Alicante',
			region: 'Comunidad Valenciana',
			year: '2023',
			leader: 'Javier Barona',
			name: 'Orihuela',
			leaderEmail: 'javbarona@gmail.com',
		},
		{
			contact: 'javbarona@gmail.com',
			coords: [38.480895, -0.969884],
			months: 'Abril-junio',
			partners: ['Javier Barona', 'María Jesús Sanchís'],
			presence: true,
			province: 'Valencia',
			region: 'Comunidad Valenciana',
			year: '2023',
			leader: 'Javier Barona',
			name: 'Solana Salinas',
			leaderEmail: 'javbarona@gmail.com',
		},
		{
			contact: 'javbarona@gmail.com',
			coords: [39.604539, -0.690746],
			months: 'Enero-marzo',
			partners: ['Javier Barona', 'María Jesús Sanchís'],
			presence: false,
			province: 'Valencia',
			region: 'Comunidad Valenciana',
			year: '2024',
			leader: 'Javier Barona',
			name: 'Vilamarxant',
			leaderEmail: 'javbarona@gmail.com',
		},
		{
			contact: 'javbarona@gmail.com',
			coords: [39.842184, -0.978345],
			months: 'Noviembre-enero',
			partners: ['Javier Barona', 'María Jesús Sanchís'],
			presence: false,
			province: 'Valencia',
			region: 'Comunidad Valenciana',
			year: '2020-2021',
			leader: 'Javier Barona',
			name: 'La yesa - Alpuente',
			leaderEmail: 'javbarona@gmail.com',
		},
		{
			contact: 'javbarona@gmail.com',
			coords: [39.995646, -0.544949],
			months: 'Julio-octubre',
			partners: ['Javier Barona', 'María Jesús Sanchís'],
			presence: true,
			province: 'Castellón',
			region: 'Comunidad Valenciana',
			year: '2023',
			leader: 'Javier Barona',
			name: 'Espadán Castellón',
			leaderEmail: 'javbarona@gmail.com',
		},
		{
			contact: 'javbarona@gmail.com',
			coords: [40.597652, 0.231764],
			months: 'Marzo-mayo',
			partners: ['Javier Barona', 'María Jesús Sanchís'],
			presence: false,
			province: 'Castellón',
			region: 'Comunidad Valenciana',
			year: '2024',
			leader: 'Javier Barona',
			name: 'Cérvol',
			leaderEmail: 'javbarona@gmail.com',
		},
		{
			contact: 'javbarona@gmail.com',
			coords: [40.417758, -0.085315],
			months: 'Enero-abril',
			partners: ['Javier Barona', 'María Jesús Sanchís'],
			presence: true,
			province: 'Castellón',
			region: 'Comunidad Valenciana',
			year: '2021',
			leader: 'Javier Barona',
			name: 'Ares del maestre',
			leaderEmail: 'javbarona@gmail.com',
		},
		{
			contact: 'javbarona@gmail.com',
			coords: [40.227822, -0.349993],
			months: 'Junio-septiembre',
			partners: ['Javier Barona', 'María Jesús Sanchís'],
			presence: true,
			province: 'Castellón',
			region: 'Comunidad Valenciana',
			year: '2020',
			leader: 'Javier Barona',
			name: 'Penyagolosa',
			leaderEmail: 'javbarona@gmail.com',
		},
		{
			contact: 'javbarona@gmail.com',
			coords: [40.674004, -0.021935],
			months: 'Julio-septiembre',
			partners: ['Javier Barona', 'María Jesús Sanchís'],
			presence: true,
			province: 'Castellón',
			region: 'Comunidad Valenciana',
			year: '2023',
			leader: 'Javier Barona',
			name: 'Herbesset',
			leaderEmail: 'javbarona@gmail.com',
		},
		{
			contact: 'javbarona@gmail.com',
			coords: [38.669728, 0.01256],
			months: 'Noviembre-enero',
			partners: ['Javier Barona', 'María Jesús Sanchís'],
			presence: false,
			province: 'Alicante',
			region: 'Comunidad Valenciana',
			year: '2024-2025',
			leader: 'Javier Barona',
			name: 'Benissa',
			leaderEmail: 'javbarona@gmail.com',
		},
		{
			contact: 'javbarona@gmail.com',
			coords: [39.964048, -0.816495],
			months: 'Diciembre-febrero',
			partners: ['Javier Barona', 'María Jesús Sanchís'],
			presence: true,
			province: 'Valencia',
			region: 'Comunidad Valenciana',
			year: '2024-2025',
			leader: 'Javier Barona',
			name: 'El Toro',
			leaderEmail: 'javbarona@gmail.com',
		},
		{
			contact: 'javbarona@gmail.com',
			coords: [39.01595, -0.638011],
			months: 'Octubre-enero',
			partners: ['Javier Barona', 'María Jesús Sanchís'],
			presence: true,
			province: 'Valencia',
			region: 'Comunidad Valenciana',
			year: '2024-2025',
			leader: 'Javier Barona',
			name: 'Sellent',
			leaderEmail: 'javbarona@gmail.com',
		},
		{
			contact: 'javbarona@gmail.com',
			coords: [40.286061, 0.154711],
			months: 'Enero-abril',
			partners: ['Javier Barona', 'María Jesús Sanchís'],
			presence: false,
			province: 'Castellón',
			region: 'Comunidad Valenciana',
			year: '2023',
			leader: 'Javier Barona',
			name: 'Coves',
			leaderEmail: 'javbarona@gmail.com',
		},
		{
			contact: 'javbarona@gmail.com',
			coords: [39.186519, -0.894913],
			months: 'Noviembre-enero',
			partners: ['Javier Barona', 'María Jesús Sanchís'],
			presence: true,
			province: 'Valencia',
			region: 'Comunidad Valenciana',
			year: '2021-2022',
			leader: 'Javier Barona',
			name: 'Muela',
			leaderEmail: 'javbarona@gmail.com',
		},
		{
			contact: 'javbarona@gmail.com',
			coords: [39.684827, -0.897986],
			months: 'Junio-agosto',
			partners: ['Javier Barona', 'María Jesús Sanchís'],
			presence: false,
			province: 'Valencia',
			region: 'Comunidad Valenciana',
			year: '2023',
			leader: 'Javier Barona',
			name: 'Losa',
			leaderEmail: 'javbarona@gmail.com',
		},
		{
			contact: 'javbarona@gmail.com',
			coords: [39.108118, -1.136393],
			months: 'Diciembre-febrero',
			partners: ['Javier Barona', 'María Jesús Sanchís'],
			presence: true,
			province: 'Valencia',
			region: 'Comunidad Valenciana',
			year: '2021-2022',
			leader: 'Javier Barona',
			name: 'Jarafuel',
			leaderEmail: 'javbarona@gmail.com',
		},
		{
			contact: 'javbarona@gmail.com',
			coords: [39.591322, -1.323475],
			months: 'Diciembre-marzo',
			partners: ['Javier Barona', 'María Jesús Sanchís'],
			presence: true,
			province: 'Valencia',
			region: 'Comunidad Valenciana',
			year: '2023-2024',
			leader: 'Javier Barona',
			name: 'Bicuerca',
			leaderEmail: 'javbarona@gmail.com',
		},
		{
			contact: 'javbarona@gmail.com',
			coords: [39.43445, -0.946988],
			months: 'Mayo-septiembre',
			partners: ['Javier Barona', 'María Jesús Sanchís'],
			presence: true,
			province: 'Valencia',
			region: 'Comunidad Valenciana',
			year: '2023',
			leader: 'Javier Barona',
			name: 'Sierra Malacara',
			leaderEmail: 'javbarona@gmail.com',
		},
		{
			contact: 'javbarona@gmail.com',
			coords: [39.815226, -0.325474],
			months: 'Diciembre-enero',
			partners: ['Javier Barona', 'María Jesús Sanchís'],
			presence: false,
			province: 'Castellón',
			region: 'Comunidad Valenciana',
			year: '2023-2024',
			leader: 'Javier Barona',
			name: 'Soneja',
			leaderEmail: 'javbarona@gmail.com',
		},
	];
}
