import { Injectable } from '@angular/core';
import { StudyArea } from '@wildcat/interfaces';

@Injectable({
	providedIn: 'root',
})
export class StudyAreaService {
	regions: String[] = [
		'Aragón',
		'Castilla La Mancha',
		'Castilla y León',
		'Extremadura',
		'Región de Murcia',
	];

	studyAreas: StudyArea[] = [
		{
			leader: 'Antonio Torrijo Pardos',
			leaderEmail: 'antorrijo@yahoo.es',
			name: 'Valdellosa',
			otherName: null,
			year: '2023',
			months: 'Febrero y Marzo',
			province: 'Teruel',
			region: 'Aragón',
			coords: [40.920251, -1.371063],
			presence: true,
			partners: [
				'José Miguel Pueyo Soler',
				'Luis Miguel Bautista Sopelana',
				'Tomas Jordán Gargallo',
			],
			contact: 'antorrijo@yahoo.es',
			link: 'https://drive.google.com/open?id=1Y2xcyr-cTZWQiorBA_u0Jkf4ZxPmxmSM, https://drive.google.com/open?id=1rWyLpMyN2mGkm1t8k15D9IMG4fIo2VVB, https://drive.google.com/open?id=1VR3ZZY-1aWIhr2PwZ-iIc1NkI_06kVZB, https://drive.google.com/open?id=15bkHquuqRkkFrP8oqJcq4cgi5oq6y8uj, https://drive.google.com/open?id=1ehxVDhvMGNliz3R5JqHI5D8KvBGBJthU, https://drive.google.com/open?id=13A3orZt1emCCtusPef8KvRt-cVevtzxG, https://drive.google.com/open?id=1LIZP6ehO_hwmhCFqgwqvtuA-Ayw5PIkW, https://drive.google.com/open?id=1xs5lAfJIeagz2XIk8Uz3eUdNYGPn2hQU, https://drive.google.com/open?id=1afjT7pB0CVzlBUm_LefPJk11xneKxPol, https://drive.google.com/open?id=1GV86owr1xGCr_N9z9kBSzpIMLN9Xxsu6',
			photos: null,
		},
		{
			leader: 'Antonio Torrijo Pardos',
			leaderEmail: 'antorrijo@yahoo.es',
			name: 'rio Camaras',
			otherName: 'Sierra de Herrera/Nogueras',
			year: '2024',
			months: 'Mayo, Junio y Julio',
			province: 'Teruel',
			region: 'Aragon',
			coords: [41.152939, -1.098953],
			presence: true,
			partners: ['José Miguel Pueyo Soler'],
			contact: 'antorrijo@yahoo.es',
			link: 'https://drive.google.com/open?id=1RN9-vFWBITBHAOtjEOH8iDVCYIqIgn85, https://drive.google.com/open?id=16GrneyFhfFSt7CAAcI-0FPjxVgcRb-NY, https://drive.google.com/open?id=1MYl14wU6b_sfAa0yuM7wmNPcW6QgkbTQ, https://drive.google.com/open?id=1V9zIUBggaaq59waTBlv4NNumjoEf_J8P, https://drive.google.com/open?id=1mp2U06kGVsNqu3P-rcnJl40cQXzhRRbN, https://drive.google.com/open?id=1AeiLcyDSTSc4RR7XoEVWsDwhKQyGORTL, https://drive.google.com/open?id=1Ig_ylN20HKC5BkjVVmitrezX0zqmTXvJ, https://drive.google.com/open?id=18BJUTR0K_-sR4YaGAiQUIbFsFGm1thb8, https://drive.google.com/open?id=1rah29Xe3gUki_cwxCSullOzla_hHWi5G, https://drive.google.com/open?id=1cPK4miSIw9xf9gW3oNddjatFSk0barIz',
			photos: null,
		},
		{
			leader: 'Aran pera natura',
			leaderEmail: 'albertofaunaran@gmail.com',
			name: "VAG (Val d'aran gat)",
			otherName: null,
			year: '2024',
			months: 'Julio, agosto, septiembre',
			province: 'Lleida',
			region: 'Catalunya',
			coords: [42.841238, 0.689718],
			presence: true,
			partners: [
				'Alberto Ginés',
				'Sara Barba',
				'Pau Ortiz',
				'Gemma Rey',
				'Javi Gil',
				'Carolina Gonzalez',
				'Eva sanchez',
				'Sandra ripoll',
				'Sara cabañas',
			],
			contact: 'albertofaunaran@gmail.com',
			link: 'https://drive.google.com/open?id=1KCA3UtEjEcZq60ca9NDbuEfs5490F8vC, https://drive.google.com/open?id=1X5rgjuGdC0RF-ryEyw-EuDAt6ffoExrZ, https://drive.google.com/open?id=1cpF56BrO4S0g3bw9Me_HccmwsSTdNwq6, https://drive.google.com/open?id=1Q_2rkhuMcii64LUYJEqmYnC_mUwP0ARo, https://drive.google.com/open?id=1eBqqR7fjNQC2ivRdSlNJ-6rpIOXAYls6',
			photos: null,
		},
		{
			leader: 'César María Aguilar Gómez',
			leaderEmail: 'tiracantos@gmail.com',
			name: 'PIEDEMONTE-VENTOSA_LR',
			otherName: null,
			year: '2023',
			months: 'Mayo a Julio',
			province: 'Logroño',
			region: 'La Rioja',
			coords: [42.51945, -4.327294],
			presence: true,
			partners: ['César María Aguilar Gómez', 'Ricardo Zaldívar López'],
			contact: 'tiracantos@gmail.com',
			link: 'https://drive.google.com/open?id=1ePbOTqJWwxOjE88caUJNDEYPxqQgRcKx, https://drive.google.com/open?id=1Gc17kOdWPeKOYQvJoXza7O9P5HlHKnUl, https://drive.google.com/open?id=14jcbob37Kx2aC63xVtGkSxPr5wqw_vMr, https://drive.google.com/open?id=1ab-mccdW-MC44WQgyGIMJnnkttCbjtfr, https://drive.google.com/open?id=1WY4hWxeHwTaS9g0pifoiZbZvu4cRo-X3, https://drive.google.com/open?id=15V2TSFsStUWjcg0NCjBlp58i2aVefUre, https://drive.google.com/open?id=10_aHCnTxLxqCQIg8RTfOjBSWsclbp6Xl, https://drive.google.com/open?id=1CXlTVEvIOex2cm5w0muzTR2PODX_oer5, https://drive.google.com/open?id=1EoyDE0EeJXlQZ4ryMiCn08m8z0KWKlRW',
			photos: null,
		},
		{
			leader: 'Cristian Osorio Huerga',
			leaderEmail: 'saliegosbirding@gmail.com',
			name: 'Zamora. Entorno al alcornocal de Cerezal de Aliste. /Ricobayo',
			otherName: null,
			year: '2023',
			months: 'My-Ag',
			province: 'Zamora',
			region: 'Castilla y León',
			coords: [41.605488, -6.02624],
			presence: false,
			partners: ['Cristian Osorio Huerga', 'José Alfredo Hernández Rodríguez'],
			contact: 'saliegosbirding@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Emilio Gonzalez Miras',
			leaderEmail: 'emiliogmiras@serbal-almeria.org',
			name: 'ZEC Sierra Cabrera-Bedar',
			otherName: 'Cabo de Gata-Cabrera',
			year: '2022',
			months: 'julio-agosto',
			province: 'Almería',
			region: 'Andalucia',
			coords: [37.112223, -1.897857],
			presence: true,
			partners: ['Emilio González Miras'],
			contact: 'emiliogmiras@serbal-almeria.org',
			link: null,
			photos: null,
		},
		{
			leader: 'Emilio González Miras',
			leaderEmail: 'emiliogmiras@serbal-almeria.org',
			name: 'Sierra de Gádor (Almería)',
			otherName: null,
			year: '2022',
			months: 'abril-julio',
			province: 'Almería',
			region: 'Andalucia',
			coords: [36.8432, -2.722902],
			presence: true,
			partners: ['Emilio González Miras'],
			contact: 'emiliogmiras@serbal-almeria.org',
			link: null,
			photos: null,
		},
		{
			leader: 'Emilio González Miras',
			leaderEmail: 'emiliogmiras@serbal-almeria.org',
			name: 'Sierra de los Filabres',
			otherName: null,
			year: '2019',
			months: 'agosto-septiembre',
			province: 'Almería',
			region: 'Andalucía',
			coords: [37.264543, -2.520795],
			presence: true,
			partners: [
				'Emilio González Miras',
				'Miguel Aguadero',
				'Mauricio Santa Trejos',
				'Jose Luis Molina',
				'Francisco Silva',
				'Francisco Sanchez Camacho',
			],
			contact: 'emiliogmiras@serbal-almeria.org',
			link: null,
			photos: null,
		},
		{
			leader: 'Emilio González Miras',
			leaderEmail: 'emiliogmiras@serbal-almeria.org',
			name: 'Desierto de Tabernas',
			otherName: null,
			year: '2019',
			months: 'octubre-noviembre',
			province: 'Almería',
			region: 'Andalucía',
			coords: [37.076831, -2.561214],
			presence: false,
			partners: ['Emilio González Miras'],
			contact: 'emiliogmiras@serbal-almeria.org',
			link: null,
			photos: null,
		},
		{
			leader: 'Enrique Fernández Larreta-Azelain',
			leaderEmail: 'elarreta@gmail.com',
			name: 'Montaña palentina',
			otherName: 'Ventosa del Pisuerga?',
			year: '2023',
			months: 'Marzo a julio',
			province: 'Palencia',
			region: 'Castilla y León',
			coords: [42.521662, -4.327356],
			presence: true,
			partners: ['Enrique Fernández Larreta-Azelain'],
			contact: 'elarreta@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Eva Carmen Rubio López',
			leaderEmail: 'evarubiolopez@hotmail.es',
			name: 'Uncastillo',
			otherName: null,
			year: '2024',
			months: 'Marzo y abril',
			province: 'Zaragoza',
			region: 'Aragón',
			coords: [42.380707, -1.105877],
			presence: true,
			partners: ['Eva Carmen Rubio López'],
			contact: 'evarubiolopez@hotmail.es',
			link: 'https://drive.google.com/open?id=1MucT1qET_4lcH8eeoRKQLyGgot0cZAkD, https://drive.google.com/open?id=1Au9VgPdZ_teOd--ZE9hsQ2-olQpoapzI, https://drive.google.com/open?id=1GOv5Z4NNkSKKZsYV_nhRWpFnYQNKgxXt, https://drive.google.com/open?id=1_vg3qOZFxxl92Rya2Ira_ht_u26IaOtP, https://drive.google.com/open?id=1-C1N9i0fM_Rqkwo3sGj4W0GawCCPVhla',
			photos: null,
		},
		{
			leader: 'Francisco Bustamante Collado',
			leaderEmail: 'pacobustamantec@gmail.com',
			name: 'Nuevo Baztan -Alcarria de Madrid',
			otherName: null,
			year: '2024',
			months: 'Febrero, marzo, abril, mayo',
			province: 'Madrid',
			region: 'Comunidad de Madrid',
			coords: [40.378331, -3.22888],
			presence: true,
			partners: [
				'Francisco Bustamante Collado',
				'Toñi Rodríguez Caballero',
				'Cristóbal Jurado Ales',
				'Eduardo Romero Fernández',
				'Helena García Bayón\nIván Salgado García\nJavier Gutiérrez Huete',
			],
			contact: 'pacobustamantec@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Francisco Javier Herrera Sanchez',
			leaderEmail: 'javher80@gmailc.om',
			name: 'Embalse la cabezuela',
			otherName: null,
			year: '2022',
			months: 'Julio-Agosto-Septiembre',
			province: 'Ciudad Real',
			region: 'Castilla la Mancha',
			coords: [38.674031, -3.190624],
			presence: true,
			partners: ['Agentes Medioambientales (Comarca de Infantes)'],
			contact: 'javher80@gmailc.om',
			link: null,
			photos: null,
		},
		{
			leader: 'Francisco Javier Herrera Sanchez',
			leaderEmail: 'javher80@gmail.com',
			name: 'Albadalejo',
			otherName: null,
			year: '2022',
			months: 'Julio-Agosto-Septiembre',
			province: 'Ciudad Real',
			region: 'Castilla La Mancha',
			coords: [38.675638, -2.829774],
			presence: true,
			partners: ['Agentes Medioambientales (Comarca de Infantes)'],
			contact: 'javher80@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Guadarrama Río de arena',
			leaderEmail: 'lberenguerg@gmail.com',
			name: 'PR Río Guadarrama',
			otherName: null,
			year: '2024-2025',
			months: 'Octubre, noviembre, diciembre y enero',
			province: 'Madrid',
			region: 'Madrid',
			coords: [40.553909, -3.837938],
			presence: false,
			partners: [
				'Alberto Díez Herrero',
				'Alicia Martínez Higuera',
				'Carolina García García',
				'Lara Berenguer Gutiérrez',
			],
			contact: 'lberenguerg@gmail.com',
			link: 'https://drive.google.com/open?id=1Zj8bFVu4elPUO95OAHbWtvhzAx4sTQSF, https://drive.google.com/open?id=14SVkvu-Au4kaDyL7CU5HGorbuzC3CvKd, https://drive.google.com/open?id=1RSG9A8bA6OicPt-GzskwLmw5LZLDnQuu, https://drive.google.com/open?id=1X0MuXI0OViUfqYH0WHoTjpIHVAEiBcvS, https://drive.google.com/open?id=1mBeFxe5at2rFbwcZ7MkPvXAWrxBAQfsP, https://drive.google.com/open?id=1_Hq1pwp3F7OB3G8BglGAyaIN8X7ii3Oi, https://drive.google.com/open?id=1MnVf0JS-S2nHOEb9dAS-8mr7PTbHuhI8, https://drive.google.com/open?id=1PpiNYSPY3D2i73RR2OF9q8XtxbhTUZ36, https://drive.google.com/open?id=1ZuWU6aZ-khqHR4O1dS-EKsCb3-tnw1tF',
			photos: null,
		},
		{
			leader: 'Guillermo Carmona Castresana',
			leaderEmail: 'guillecarmonacastresana@gmail.com',
			name: 'Aldealbar',
			otherName: null,
			year: '2021',
			months: 'Noviembre - diciembre',
			province: 'Valladolid',
			region: 'Castilla y León',
			coords: [41.471135, -4.358193],
			presence: true,
			partners: ['Guillermo Carmona Castresana'],
			contact: 'guillecarmonacastresana@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Guillermo Carmona Castresana',
			leaderEmail: 'guillecarmonacastresana@gmail.com',
			name: 'Cevico Navero',
			otherName: null,
			year: '2021',
			months: 'Noviembre - diciembre',
			province: 'Palencia',
			region: 'Castilla y León',
			coords: [41.849617, -4.182623],
			presence: true,
			partners: ['Guillermo Carmona Castresana'],
			contact: 'guillecarmonacastresana@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Héctor Ruiz Villar',
			leaderEmail: 'chinhector@gmail.com',
			name: 'Alto Sil leonés',
			otherName: 'Occidente Cordillera Cantábrica',
			year: '2021',
			months: 'Marzo a Mayo',
			province: 'León',
			region: 'Castilla y León',
			coords: [42.931609, -6.387837],
			presence: true,
			partners: [
				'Héctor Ruiz Villar',
				'Ana Morales González',
				'Ezequiel Martínez Vera',
				'Florentino Ruiz Barreiro',
			],
			contact: 'chinhector@gmail.com',
			link: 'https://drive.google.com/open?id=1Y41Y3sbPJ-RgK4HkpqfW9DlOW0tbq3eO, https://drive.google.com/open?id=1RNN018y13DCeyXVenFt1tAecVpFy-kiD, https://drive.google.com/open?id=1aGlK-XQeHgv_znd221U9BMWxzmsVgyfr, https://drive.google.com/open?id=1whm2ipn61_kP0fLQJtlkSaxWBYzFe6Na, https://drive.google.com/open?id=1lJAB2l1nnUstjkIO_CE1I7xA9sVI1ifs, https://drive.google.com/open?id=1O7cvmBrAHzu4BbM0XAYa0nSWV6i5jJj1, https://drive.google.com/open?id=1h84R_fQiuH9pHIj6dOtC_7HPix4c105z, https://drive.google.com/open?id=1OVRyEY-MDcOtqcA7GuUNMuVrYp0gX09c, https://drive.google.com/open?id=1nuXdpyKyj11bFp1yjIdIRrua-AuVI32G, https://drive.google.com/open?id=19p6w4yXqFHFe5kQ3dWWAB1L8THwCrV5N',
			photos: null,
		},
		{
			leader: 'Jordi Bermejo Cabezas',
			leaderEmail: 'bermejonatur@hotmail.com',
			name: 'Girona (Vall del Llémena)',
			otherName: null,
			year: '2019',
			months: 'Octubre/Noviembre//Diciembre',
			province: 'Girona',
			region: 'Catalunya',
			coords: [42.122781, 2.546384],
			presence: true,
			partners: ['Isidre Cos Arnau'],
			contact: 'bermejonatur@hotmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Jose Miguel Aguilar Serrano',
			leaderEmail: 'josemiguel.aguilar11@gmail.com',
			name: 'Sierra de Espadán NW (Sierra de Caudiel)',
			otherName: 'Sierra de Caudiel, Sierra de ESPADÁN NW',
			year: '2023',
			months: 'julio 2023-octubre 2023',
			province: 'Castellón',
			region: 'Comunidad Valenciana',
			coords: [39.991128, -0.552938],
			presence: true,
			partners: [
				'Jose Miguel Aguilar Serrano\nSantiago Marco Gracia\nFrancisco Javier Lloris Martínez\nFrancisco García López\nJose Giménez Segarra',
			],
			contact: 'josemiguel.aguilar11@gmail.com',
			link: 'https://drive.google.com/open?id=1xUWmFWOL1CT0P4JhfjV3gQA4gLC-sIa6, https://drive.google.com/open?id=1UkqOV2linRfGtImWlt_d979LKy4i66L7, https://drive.google.com/open?id=1tg0odOmYZQnf3yYmBhp2enEFXzxRrB7u, https://drive.google.com/open?id=10zABXVAAeqgGxxTfty6tOSGj0BjQPhom, https://drive.google.com/open?id=17MDCNch57t-2zS0PQRUHHbl7UiDY_9nr, https://drive.google.com/open?id=1-rJ2zpFLwBlYYfpmdE6pEJaETCDSCIQ9, https://drive.google.com/open?id=1CSsAUpyr2KQ5EmadQ5_esym7-zzi-QPC, https://drive.google.com/open?id=1jvqI58l7sEilwSfXcYg6zLyoC7JJ-h-o, https://drive.google.com/open?id=18eK9RBt7hQZ0smNNzGoEJI13Yyoab799',
			photos: null,
		},
		{
			leader: 'Jose Miguel Aguilar Serrano',
			leaderEmail: 'josemiguel.aguilar11@gmail.com',
			name: 'Sierra de El Toro',
			otherName: 'Sierra de El Toro, SW Sistema ibérico',
			year: '2024',
			months: 'diciembre 2024- marzo 2025',
			province: 'Castellón',
			region: 'Comunidad Valenciana',
			coords: [39.958775, -0.809982],
			presence: true,
			partners: [
				'Jose Miguel Aguilar Serrano\nSantiago Marco Gracia\nEusebio García Orduña\nManuel García Tarrasón\nFrancisco Javier Lloris Martínez',
			],
			contact: 'josemiguel.aguilar11@gmail.com',
			link: 'https://drive.google.com/open?id=1-f25lpe414rVInwN19WvMmbhVPwRxU2B, https://drive.google.com/open?id=1VHZ7lLwfhPYah1JWsdjEqqIWrJqpDv13, https://drive.google.com/open?id=19XtzxectsT49hOZc6ljMJ2nkwp8OfDFk, https://drive.google.com/open?id=1qlT7u3UhXVUr1foSytFPdn4r5ggI6EAK, https://drive.google.com/open?id=1daWq0D_o426aA1LvyOJmlaBBr9oTA7JT, https://drive.google.com/open?id=1oti5X50RZxXD5nIqHUAIW5JRoqdCQ-fB, https://drive.google.com/open?id=1ZLZmdR_ItSiWalXNny9usBcLYjWUPMCG, https://drive.google.com/open?id=1heqsgD8-fbiaHZFyKcNXzSOtFuYhb6qH, https://drive.google.com/open?id=1PpL2qekN4Lp49a3Vzv-Fx29t2mOJXZla, https://drive.google.com/open?id=1Zjvt1DDjg7OX1BjeyBWfSO7jv0eU0qnE',
			photos: null,
		},
		{
			leader: 'Jose Miguel Gomez Sanchez',
			leaderEmail: 'eleusis38@hotmail.com',
			name: 'Sierra Estancias (Almeria)',
			otherName: null,
			year: '2021',
			months: 'Enero, febrero, marzo y abril',
			province: 'Almeria',
			region: 'Andalucia',
			coords: [37.578635, -2.038166],
			presence: true,
			partners: [
				'Ana Belen Martinez Parra',
				'Gines Jesus Gomez Sanchez',
				'Blas Gonzalez Martinez',
				'Jose Miguel Gomez Sanchez',
			],
			contact: 'eleusis38@hotmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Julián Castaño Soriano',
			leaderEmail: 'juliancsoriano47@gmail.com',
			name: 'Monte Arabí - Yecla',
			otherName: null,
			year: '2024',
			months: 'Junio/Julio',
			province: 'Murcia',
			region: 'Región de Murcia',
			coords: [38.731319, -1.226226],
			presence: true,
			partners: [
				'Julián Castaño Soriano (Asociación Naturalista para la Investigación y Defensa del Altiplano-ANIDA)',
			],
			contact: 'juliancsoriano47@gmail.com',
			link: 'https://drive.google.com/open?id=16mzrGxhkY4bY0KAImib0RBAhWVIFxKVn, https://drive.google.com/open?id=14FMyHaqc8pFhMJlFFjcM9l9uk_WSEAum, https://drive.google.com/open?id=1IkbJXYVzYifoAhdUNxGrlgqiZ4ApXBXc, https://drive.google.com/open?id=1sPbJQxfYCsjDWesg7sAqVDN4WCjZURdZ, https://drive.google.com/open?id=1RFIADhvVeKxivshjF6ERaPN_pCOlHWCK, https://drive.google.com/open?id=1JDQTOA3u1YkthkehJt-uBglrN9rlULz7, https://drive.google.com/open?id=1kOBPhrf7lg9d3u6Jz4jidP9a-T-uGy9f, https://drive.google.com/open?id=12rPEqAJ2iOR7CVwmvC7KN495JDFCvNpL, https://drive.google.com/open?id=14cafAUlbS2r1ugYt9qoAGswIkJiBVxXN, https://drive.google.com/open?id=1Aj1CH4kUaZym1yDL-UI3D0P5ypVC141F',
			photos: null,
		},
		{
			leader: 'Julián Martín Garde',
			leaderEmail: 'jmgdrosera@gmail.com',
			name: 'Sierra de Francia',
			otherName: null,
			year: '2022',
			months: 'Enero a abril',
			province: 'Salamanca',
			region: 'Castilla y León',
			coords: [40.510273, -6.109444],
			presence: false,
			partners: ['Julián Martín Garde'],
			contact: 'jmgdrosera@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Lope Lorenzo Martínez',
			leaderEmail: 'lope.lorenzo@gmail.com',
			name: 'Nerpio',
			otherName: null,
			year: '2021',
			months: 'Mayo, junio, julio (retiradas: 4 julio)',
			province: 'Albacete',
			region: 'Castilla-La Mancha',
			coords: [38.154884, -2.350179],
			presence: false,
			partners: ['Trino Ferrández', 'Chema Catarineu', 'Lope Lorenzo'],
			contact: 'lope.lorenzo@gmail.com',
			link: 'https://drive.google.com/open?id=1oRDgmFw45m6g-YKVDr29kKwXcylg-fKB, https://drive.google.com/open?id=1AEf3BF87TWN3pQ2yWGakjt8Lu1dStlFd, https://drive.google.com/open?id=1rlbB5sDPs89XQoybRrvc0K57fQO68gDh, https://drive.google.com/open?id=1g86N1oSNZ5wX88h49J6f6GXEk3cHQEhz, https://drive.google.com/open?id=1jMm4BU0xcncGclkhw6k8l_pUYjscbYVO',
			photos: null,
		},
		{
			leader: 'Loreto García Román',
			leaderEmail: 'lorejaruco@gmail.com',
			name: 'Parque Regional del Sureste',
			otherName: null,
			year: '2024',
			months: 'Abril-junio',
			province: 'Madrid',
			region: 'Comunidad de Madrid',
			coords: [40.4168, -3.7038],
			presence: false,
			partners: [
				'Loreto García Román',
				'Felipe Peñalosa García',
				'Félix Martínez Olivas',
				'Jorge Calero Ramírez',
			],
			contact: 'lorejaruco@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Marc Vilella Antonell',
			leaderEmail: 'marc.vilella16@gmail.com',
			name: 'Sant Pere Torello (BCN)',
			otherName: null,
			year: '2021',
			months: 'febrero, marzo, abril',
			province: 'Barcelona',
			region: 'Catalunya',
			coords: [42.107995, 2.362039],
			presence: true,
			partners: [
				'Ferran Sayol',
				'Eric Serratosa',
				'Marc Rota',
				'Xevi Arumí',
				'Alfred Encuentra',
				'Marc Vilella',
			],
			contact: 'marc.vilella16@gmail.com',
			link: 'https://drive.google.com/open?id=1fh9J14AKQqdrWfVqJfZGysMFNVqplF-s, https://drive.google.com/open?id=18ioXVyKuOFCS_ZpJ6-5tZbYLZ5NBBeWJ, https://drive.google.com/open?id=1-qnt8Y98I8lkqk3Zr5Z_FS53WSgw0Nzh, https://drive.google.com/open?id=1Lb_uCToJ6DFBT9KZyLLbwL6CCUXngcNi, https://drive.google.com/open?id=1uYXXYydFjdE_MgNh-GiR2QepcV9D5dsZ, https://drive.google.com/open?id=1GC6iQHzYA8dvVxmfw0PYPhOgsANVrZa_, https://drive.google.com/open?id=1iOaFrsPg1U3aWOc9M_7G4q9hGvkPrp53, https://drive.google.com/open?id=1GLmCDEyjMu52D_XuApcDK8V2EMiQIX9A, https://drive.google.com/open?id=1vQInhEoISUpSYRBMkL2iP2apWkSC546I, https://drive.google.com/open?id=1KDEX4KfZdb0zaLgiKKOVhADFmO4wAkAb',
			photos: null,
		},
		{
			leader: 'Miguel Ángel Pena Ferrer',
			leaderEmail: 'juanodecinca@gmail.com',
			name: 'Monegros',
			otherName: 'Sierra de Sigena',
			year: '2021-2022',
			months: 'Diciembre Enero Febrero',
			province: 'Huesca',
			region: 'Aragón',
			coords: [41.572451, -0.080716],
			presence: true,
			partners: ['Miguel Ángel Pena Ferrer'],
			contact: 'juanodecinca@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Pablo Monroy Martínez',
			leaderEmail: 'pablomonroymartinez@gmail.com',
			name: 'Sierra de la Virgen',
			otherName: 'Zaragoza',
			year: '2020',
			months: 'Junio, julio y agosto',
			province: 'Zaragoza',
			region: 'Aragón',
			coords: [41.518349, -1.736418],
			presence: true,
			partners: ['Pablo Monroy'],
			contact: 'pablomonroymartinez@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Uge Fuertes Sanz',
			leaderEmail: 'Chavaldelapetra@gmail.com',
			name: 'Sierra caldereros',
			otherName: null,
			year: '2024',
			months: 'Abril mayo',
			province: 'Guadajara',
			region: 'Castilla la Mancha',
			coords: [40.839059, -1.70625],
			presence: true,
			partners: ['Uge Fuertes Sanz'],
			contact: 'Chavaldelapetra@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Javier Hernández',
			leaderEmail: 'javierhh95@gmail.com',
			name: 'Sª Gredos',
			otherName: 'Navamorcuende- El Real de San Vicente',
			year: '2022',
			months: 'Febrero-abril',
			province: 'Toledo',
			region: 'Castilla la Mancha',
			coords: [40.158403, -4.728151],
			presence: true,
			partners: ['Javier Hernández', 'Emilio Virgós'],
			contact: 'javierhh95@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Javier Hernández',
			leaderEmail: 'javierhh95@gmail.com',
			name: 'Alto tajo',
			otherName: 'Zaorejas',
			year: '2022',
			months: 'Enero-abril',
			province: 'Guadajara',
			region: 'Castilla la Mancha',
			coords: [40.724643, -2.345086],
			presence: true,
			partners: ['Javier Hernández', 'Emilio Virgós'],
			contact: 'javierhh95@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Javier Hernández',
			leaderEmail: 'javierhh95@gmail.com',
			name: 'Hoyo de Pinares',
			otherName: null,
			year: '2021',
			months: 'Junio-agosto',
			province: 'Ávila',
			region: 'Castilla y León',
			coords: [40.517663, -4.359074],
			presence: false,
			partners: ['Javier Hernández', 'Emilio Virgós'],
			contact: 'javierhh95@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Javier Hernández',
			leaderEmail: 'javierhh95@gmail.com',
			name: 'Erro',
			otherName: 'Zilbeti',
			year: '2022',
			months: 'Junio-diciembre',
			province: 'Navarra',
			region: 'Comunidad Foral de Navarra',
			coords: [42.954473, -1.471698],
			presence: true,
			partners: ['Javier Hernández'],
			contact: 'javierhh95@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Javier Hernández',
			leaderEmail: 'javierhh95@gmail.com',
			name: 'Almazán',
			otherName: 'Soria',
			year: '2022',
			months: 'Febrero-abril',
			province: 'Soria',
			region: 'Castilla y León',
			coords: [41.552081, -2.576438],
			presence: true,
			partners: ['Javier Hernández', 'Emilio Virgós'],
			contact: 'javierhh95@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Javier Hernández',
			leaderEmail: 'javierhh95@gmail.com',
			name: 'Robledillo de la Jara',
			otherName: null,
			year: '2021',
			months: 'Febrero-abril',
			province: 'Madrid',
			region: 'Comunidad de Madrid',
			coords: [40.96278, -3.503573],
			presence: true,
			partners: ['Javier Hernández', 'Emilio Virgós'],
			contact: 'javierhh95@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Javier Hernández',
			leaderEmail: 'javierhh95@gmail.com',
			name: 'Cillán',
			otherName: 'Ávila/Horcajuelo',
			year: '2022',
			months: 'Julio-noviembre',
			province: 'Ávila',
			region: 'Castilla y León',
			coords: [40.727144, -4.929763],
			presence: true,
			partners: ['Javier Hernández', 'Emilio Virgós'],
			contact: 'javierhh95@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Javier Hernández',
			leaderEmail: 'javierhh95@gmail.com',
			name: 'Alto de cabreja',
			otherName: null,
			year: '2021',
			months: 'Mayo-julio',
			province: 'Cuenca',
			region: 'Castilla la Mancha',
			coords: [40.105079, -2.509681],
			presence: true,
			partners: ['Javier Hernández', 'Emilio Virgós'],
			contact: 'javierhh95@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Javier Hernández',
			leaderEmail: 'javierhh95@gmail.com',
			name: 'Carabaña',
			otherName: null,
			year: '2020-2021',
			months: 'Noviembre-enero',
			province: 'Madrid',
			region: 'Comunidad de Madrid',
			coords: [40.24151, -3.228976],
			presence: true,
			partners: ['Javier Hernández', 'Tamara Burgos', 'Emilio Virgós'],
			contact: 'javierhh95@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Javier Barona',
			leaderEmail: 'javbarona@gmail.com',
			name: 'Albosa',
			otherName: null,
			year: '2020',
			months: 'Febrero-junio',
			province: 'Valencia',
			region: 'Comunidad Valenciana',
			coords: [39.404687, -1.223058],
			presence: true,
			partners: ['Javier Barona', 'María Jesús Sanchís'],
			contact: 'javbarona@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Javier Barona',
			leaderEmail: 'javbarona@gmail.com',
			name: 'Moixent',
			otherName: null,
			year: '2024',
			months: 'Marzo-mayo',
			province: 'Alicante',
			region: 'Comunidad Valenciana',
			coords: [38.823724, -0.823898],
			presence: true,
			partners: ['Javier Barona', 'María Jesús Sanchís'],
			contact: 'javbarona@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Javier Barona',
			leaderEmail: 'javbarona@gmail.com',
			name: 'Aitana',
			otherName: null,
			year: '2022',
			months: 'Junio-julio',
			province: 'Alicante',
			region: 'Comunidad Valenciana',
			coords: [38.63617, -0.329426],
			presence: true,
			partners: ['Javier Barona', 'María Jesús Sanchís'],
			contact: 'javbarona@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Javier Barona',
			leaderEmail: 'javbarona@gmail.com',
			name: 'Castalla Arguenya',
			otherName: null,
			year: '2020',
			months: 'Octubre-diciembre',
			province: 'Alicante',
			region: 'Comunidad Valenciana',
			coords: [38.586843, -0.740331],
			presence: true,
			partners: ['Javier Barona', 'María Jesús Sanchís'],
			contact: 'javbarona@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Javier Barona',
			leaderEmail: 'javbarona@gmail.com',
			name: 'Font Roja',
			otherName: null,
			year: '2022',
			months: 'Julio-septiembre',
			province: 'Alicante',
			region: 'Comunidad Valenciana',
			coords: [38.674627, -0.575566],
			presence: false,
			partners: ['Javier Barona', 'María Jesús Sanchís'],
			contact: 'javbarona@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Javier Barona',
			leaderEmail: 'javbarona@gmail.com',
			name: 'Barx',
			otherName: null,
			year: '2023',
			months: 'Octubre-diciembre',
			province: 'Valencia',
			region: 'Comunidad Valenciana',
			coords: [38.994191, -0.394738],
			presence: true,
			partners: ['Javier Barona', 'María Jesús Sanchís'],
			contact: 'javbarona@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Javier Barona',
			leaderEmail: 'javbarona@gmail.com',
			name: 'Beniarrés',
			otherName: null,
			year: '2023',
			months: 'Abril-junio',
			province: 'Alicante',
			region: 'Comunidad Valenciana',
			coords: [38.781966, -0.375583],
			presence: true,
			partners: ['Javier Barona', 'María Jesús Sanchís'],
			contact: 'javbarona@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Javier Barona',
			leaderEmail: 'javbarona@gmail.com',
			name: 'Cabeso DOr',
			otherName: null,
			year: '2024',
			months: 'Marzo-junio',
			province: 'Alicante',
			region: 'Comunidad Valenciana',
			coords: [38.547347, -0.444166],
			presence: false,
			partners: ['Javier Barona', 'María Jesús Sanchís'],
			contact: 'javbarona@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Javier Barona',
			leaderEmail: 'javbarona@gmail.com',
			name: 'Crevillente',
			otherName: null,
			year: '2024',
			months: 'Enero-febrero',
			province: 'Alicante',
			region: 'Comunidad Valenciana',
			coords: [38.276542, -0.862306],
			presence: false,
			partners: ['Javier Barona', 'María Jesús Sanchís'],
			contact: 'javbarona@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Javier Barona',
			leaderEmail: 'javbarona@gmail.com',
			name: 'Orihuela',
			otherName: null,
			year: '2023',
			months: 'Septiembre-noviembre',
			province: 'Alicante',
			region: 'Comunidad Valenciana',
			coords: [37.93321, -0.861585],
			presence: true,
			partners: ['Javier Barona', 'María Jesús Sanchís'],
			contact: 'javbarona@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Javier Barona',
			leaderEmail: 'javbarona@gmail.com',
			name: 'Solana Salinas',
			otherName: null,
			year: '2023',
			months: 'Abril-junio',
			province: 'Valencia',
			region: 'Comunidad Valenciana',
			coords: [38.480895, -0.969884],
			presence: true,
			partners: ['Javier Barona', 'María Jesús Sanchís'],
			contact: 'javbarona@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Javier Barona',
			leaderEmail: 'javbarona@gmail.com',
			name: 'Vilamarxant',
			otherName: null,
			year: '2024',
			months: 'Enero-marzo',
			province: 'Valencia',
			region: 'Comunidad Valenciana',
			coords: [39.604539, -0.690746],
			presence: false,
			partners: ['Javier Barona', 'María Jesús Sanchís'],
			contact: 'javbarona@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Javier Barona',
			leaderEmail: 'javbarona@gmail.com',
			name: 'La yesa - Alpuente',
			otherName: null,
			year: '2020-2021',
			months: 'Noviembre-enero',
			province: 'Valencia',
			region: 'Comunidad Valenciana',
			coords: [39.842184, -0.978345],
			presence: false,
			partners: ['Javier Barona', 'María Jesús Sanchís'],
			contact: 'javbarona@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Javier Barona',
			leaderEmail: 'javbarona@gmail.com',
			name: 'Espadán Castellón',
			otherName: null,
			year: '2023',
			months: 'Julio-octubre',
			province: 'Castellón',
			region: 'Comunidad Valenciana',
			coords: [39.995646, -0.544949],
			presence: true,
			partners: ['Javier Barona', 'María Jesús Sanchís'],
			contact: 'javbarona@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Javier Barona',
			leaderEmail: 'javbarona@gmail.com',
			name: 'Cérvol',
			otherName: null,
			year: '2024',
			months: 'Marzo-mayo',
			province: 'Castellón',
			region: 'Comunidad Valenciana',
			coords: [40.597652, 0.231764],
			presence: false,
			partners: ['Javier Barona', 'María Jesús Sanchís'],
			contact: 'javbarona@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Javier Barona',
			leaderEmail: 'javbarona@gmail.com',
			name: 'Ares del maestre',
			otherName: null,
			year: '2021',
			months: 'Enero-abril',
			province: 'Castellón',
			region: 'Comunidad Valenciana',
			coords: [40.417758, -0.085315],
			presence: true,
			partners: ['Javier Barona', 'María Jesús Sanchís'],
			contact: 'javbarona@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Javier Barona',
			leaderEmail: 'javbarona@gmail.com',
			name: 'Penyagolosa',
			otherName: null,
			year: '2020',
			months: 'Junio-septiembre',
			province: 'Castellón',
			region: 'Comunidad Valenciana',
			coords: [40.227822, -0.349993],
			presence: true,
			partners: ['Javier Barona', 'María Jesús Sanchís'],
			contact: 'javbarona@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Javier Barona',
			leaderEmail: 'javbarona@gmail.com',
			name: 'Herbesset',
			otherName: null,
			year: '2023',
			months: 'Julio-septiembre',
			province: 'Castellón',
			region: 'Comunidad Valenciana',
			coords: [40.674004, -0.021935],
			presence: true,
			partners: ['Javier Barona', 'María Jesús Sanchís'],
			contact: 'javbarona@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Javier Barona',
			leaderEmail: 'javbarona@gmail.com',
			name: 'Benissa',
			otherName: null,
			year: '2024-2025',
			months: 'Noviembre-enero',
			province: 'Alicante',
			region: 'Comunidad Valenciana',
			coords: [38.669728, 0.01256],
			presence: false,
			partners: ['Javier Barona', 'María Jesús Sanchís'],
			contact: 'javbarona@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Javier Barona',
			leaderEmail: 'javbarona@gmail.com',
			name: 'El Toro',
			otherName: null,
			year: '2024-2025',
			months: 'Diciembre-febrero',
			province: 'Valencia',
			region: 'Comunidad Valenciana',
			coords: [39.964048, -0.816495],
			presence: true,
			partners: ['Javier Barona', 'María Jesús Sanchís'],
			contact: 'javbarona@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Javier Barona',
			leaderEmail: 'javbarona@gmail.com',
			name: 'Sellent',
			otherName: null,
			year: '2024-2025',
			months: 'Octubre-enero',
			province: 'Valencia',
			region: 'Comunidad Valenciana',
			coords: [39.01595, -0.638011],
			presence: true,
			partners: ['Javier Barona', 'María Jesús Sanchís'],
			contact: 'javbarona@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Javier Barona',
			leaderEmail: 'javbarona@gmail.com',
			name: 'Coves',
			otherName: null,
			year: '2023',
			months: 'Enero-abril',
			province: 'Castellón',
			region: 'Comunidad Valenciana',
			coords: [40.286061, 0.154711],
			presence: false,
			partners: ['Javier Barona', 'María Jesús Sanchís'],
			contact: 'javbarona@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Javier Barona',
			leaderEmail: 'javbarona@gmail.com',
			name: 'Muela',
			otherName: null,
			year: '2021-2022',
			months: 'Noviembre-enero',
			province: 'Valencia',
			region: 'Comunidad Valenciana',
			coords: [39.186519, -0.894913],
			presence: true,
			partners: ['Javier Barona', 'María Jesús Sanchís'],
			contact: 'javbarona@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Javier Barona',
			leaderEmail: 'javbarona@gmail.com',
			name: 'Losa',
			otherName: null,
			year: '2023',
			months: 'Junio-agosto',
			province: 'Valencia',
			region: 'Comunidad Valenciana',
			coords: [39.684827, -0.897986],
			presence: false,
			partners: ['Javier Barona', 'María Jesús Sanchís'],
			contact: 'javbarona@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Javier Barona',
			leaderEmail: 'javbarona@gmail.com',
			name: 'Jarafuel',
			otherName: null,
			year: '2021-2022',
			months: 'Diciembre-febrero',
			province: 'Valencia',
			region: 'Comunidad Valenciana',
			coords: [39.108118, -1.136393],
			presence: true,
			partners: ['Javier Barona', 'María Jesús Sanchís'],
			contact: 'javbarona@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Javier Barona',
			leaderEmail: 'javbarona@gmail.com',
			name: 'Bicuerca',
			otherName: null,
			year: '2023-2024',
			months: 'Diciembre-marzo',
			province: 'Valencia',
			region: 'Comunidad Valenciana',
			coords: [39.591322, -1.323475],
			presence: true,
			partners: ['Javier Barona', 'María Jesús Sanchís'],
			contact: 'javbarona@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Javier Barona',
			leaderEmail: 'javbarona@gmail.com',
			name: 'Sierra Malacara',
			otherName: null,
			year: '2023',
			months: 'Mayo-septiembre',
			province: 'Valencia',
			region: 'Comunidad Valenciana',
			coords: [39.43445, -0.946988],
			presence: true,
			partners: ['Javier Barona', 'María Jesús Sanchís'],
			contact: 'javbarona@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Javier Barona',
			leaderEmail: 'javbarona@gmail.com',
			name: 'Soneja',
			otherName: null,
			year: '2023-2024',
			months: 'Diciembre-enero',
			province: 'Castellón',
			region: 'Comunidad Valenciana',
			coords: [39.815226, -0.325474],
			presence: false,
			partners: ['Javier Barona', 'María Jesús Sanchís'],
			contact: 'javbarona@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'David Sánchez Sotomayor',
			leaderEmail: 'iberozoa@gmail.com',
			name: 'Los Hinojosos',
			otherName: null,
			year: '2025',
			months: 'Abril-julio',
			province: 'Cuenca',
			region: 'Castilla la Mancha',
			coords: [39.631984, -2.878576],
			presence: false,
			partners: ['David Sánchez', 'Mateo Lamas'],
			contact: 'iberozoa@gmail.com',
			link: 'https://drive.google.com/open?id=1JE2oBlMufpBJh3lasUby8mCOEyhQj1id',
			photos: null,
		},
		{
			leader: 'David Sánchez Sotomayor',
			leaderEmail: 'iberozoa@gmail.com',
			name: 'Garvín',
			otherName: null,
			year: '2025',
			months: 'Abril-julio',
			province: 'Toledo',
			region: 'Castilla la Mancha',
			coords: [39.6939131, -5.3098743],
			presence: false,
			partners: ['David Sánchez', 'Mateo Lamas'],
			contact: 'iberozoa@gmail.com',
			link: 'https://drive.google.com/open?id=1yS4S3_FdiEwaiDmKE-kiSBJ0Y6SORqxk',
			photos: null,
		},
		{
			leader: 'David Sánchez Sotomayor',
			leaderEmail: 'iberozoa@gmail.com',
			name: 'Gata',
			otherName: null,
			year: '2025',
			months: 'Abril-julio',
			province: 'Cáceres',
			region: 'Extremadura',
			coords: [40.2715717, -6.5703147],
			presence: false,
			partners: ['David Sánchez', 'Mateo Lamas'],
			contact: 'iberozoa@gmail.com',
			link: 'https://drive.google.com/open?id=13Sg-jItKD1qcenKT-QvpFyppDvclaxz5',
			photos: null,
		},
		{
			leader: 'Pedro L. Ramos Bueno',
			leaderEmail: 'plramosbueno@gmail.com',
			name: 'Larrodrigo - Diego del Carpio',
			otherName: 'Diego del Carpio',
			year: '2023',
			months: 'Agosto-Octubre',
			province: 'Salamanca y Avila',
			region: 'Castilla y León',
			coords: [40.6924, -5.415],
			presence: true,
			partners: ['Pedro L. Ramos', 'Juan Ramón Rodriguez'],
			contact: 'plramosbueno@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Pedro L. Ramos Bueno',
			leaderEmail: 'plramosbueno@gmail.com',
			name: 'Valdelosa - Mayalde',
			otherName: 'Valdelosa',
			year: '2023',
			months: 'Marzo - Abril',
			province: 'Salamanca y Zamora',
			region: 'Castilla y León',
			coords: [41.2084, -5.784],
			presence: false,
			partners: [
				'Pedro L. Ramos',
				'Enrique Vicente',
				'Juan Manuel González',
				'Susana Comuñas',
				'Miguel Angel G. Samaniego',
			],
			contact: 'plramosbueno@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Pedro L. Ramos Bueno',
			leaderEmail: 'plramosbueno@gmail.com',
			name: 'Gallegos de Solmirón - Sta. María del Berrocal',
			otherName: 'Gallegos de Solmirón',
			year: '2023',
			months: 'Agosto-octubre',
			province: 'Salamanca y Ávila',
			region: 'Castilla y León',
			coords: [40.519, -5.448],
			presence: true,
			partners: [
				'Pedro L. Ramos',
				'Miguel Angel Gzlez. Samaniego',
				'Gustavo A. Merchán',
				'Adolfo M. Rguez.',
			],
			contact: 'plramosbueno@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Pedro L. Ramos Bueno',
			leaderEmail: 'plramosbueno@gmail.com',
			name: 'Sobradillo P.N. Arribes del Duero',
			otherName: 'Sobradillo P.N. Arribes Duero-Águeda',
			year: '2024',
			months: 'Marzo-mayo',
			province: 'Salamanca',
			region: 'Castilla y León',
			coords: [40.9433, -6.83],
			presence: false,
			partners: [
				'Pedro L. Ramos',
				'Roberto Carbonell',
				'Carlos Sánchez',
				'Estefanía Alvarez',
				'Rodrigo Pascual',
			],
			contact: 'plramosbueno@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Pedro L. Ramos Bueno',
			leaderEmail: 'plramosbueno@gmail.com',
			name: 'Valle del Agadón (Monsagro-Serradilla del Llano)',
			otherName: 'Monsagro-Serradilla del Llano',
			year: '2024',
			months: 'Diciembre-marzo',
			province: 'Salamanca',
			region: 'Castilla y León',
			coords: [40.4787, -6.34],
			presence: true,
			partners: [
				'Pedro L. Ramos',
				'Pablo Matas',
				'Ramón Román',
				'Anabel Baladrón',
			],
			contact: 'plramosbueno@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Carmen Díez Rivera',
			leaderEmail: 'marcosmallo@gmail.com',
			name: 'Xurés',
			otherName: 'Serra do Xurés',
			year: '2019',
			months: 'Diciembre-enero',
			province: 'Ourense',
			region: 'Galicia',
			coords: [41.8979698, -7.9595444],
			presence: true,
			partners: [
				'Marcos Mallo-Leira',
				'Carmen Díez-Rivera',
				'Sahara Ugatz Mallo',
			],
			contact: 'marcosmallo@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Carmen Díez Rivera',
			leaderEmail: 'marcosmallo@gmail.com',
			name: 'Serra do Suído',
			otherName: 'Sierra del Suído',
			year: '2020',
			months: 'Febrero-mayo',
			province: 'Pontevedra',
			region: 'Galicia',
			coords: [42.4035464, -8.3363217],
			presence: true,
			partners: [
				'Marcos Mallo-Leira',
				'Carmen Díez-Rivera',
				'Sahara Ugatz Mallo',
			],
			contact: 'marcosmallo@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Carmen Díez Rivera',
			leaderEmail: 'marcosmallo@gmail.com',
			name: 'Queixa',
			otherName: 'Serra de Queixa',
			year: '2020',
			months: 'Junio-septiembre',
			province: 'Ourense',
			region: 'Galicia',
			coords: [42.2923437, -7.3536844],
			presence: true,
			partners: [
				'Marcos Mallo-Leira',
				'Carmen Díez-Rivera',
				'Sahara Ugatz Mallo',
			],
			contact: 'marcosmallo@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Carmen Díez Rivera',
			leaderEmail: 'marcosmallo@gmail.com',
			name: 'Ancares',
			otherName: null,
			year: '2020',
			months: 'Noviembre-febrero',
			province: 'Lugo',
			region: 'Galicia',
			coords: [42.6308566, -7.1076309],
			presence: true,
			partners: [
				'Marcos Mallo-Leira',
				'Carmen Díez-Rivera',
				'Sahara Ugatz Mallo',
			],
			contact: 'marcosmallo@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Marcos Mallo Leira',
			leaderEmail: 'marcosmallo@gmail.com',
			name: 'Serra do Xistral',
			otherName: 'Xistral',
			year: '2021',
			months: 'Febrero-abril',
			province: 'A Coruña / Lugo',
			region: 'Galicia',
			coords: [43.4680094, -7.5716306],
			presence: true,
			partners: [
				'Marcos Mallo-Leira',
				'Carmen Díez-Rivera',
				'Sahara Ugatz Mallo',
			],
			contact: 'marcosmallo@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Marcos Mallo Leira',
			leaderEmail: 'marcosmallo@gmail.com',
			name: 'Ulla',
			otherName: null,
			year: '2021',
			months: 'Mayo-julio',
			province: 'Pontevedra / A Coruña',
			region: 'Galicia',
			coords: [42.8303948, -8.2654034],
			presence: false,
			partners: [
				'Marcos Mallo-Leira',
				'Carmen Díez-Rivera',
				'Sahara Ugatz Mallo',
			],
			contact: 'marcosmallo@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Carmen Díez Rivera',
			leaderEmail: 'marcosmallo@gmail.com',
			name: 'Allariz',
			otherName: null,
			year: '2021',
			months: 'Agosto-octubre',
			province: 'Ourense',
			region: 'Galicia',
			coords: [42.1674087, -7.7794009],
			presence: false,
			partners: [
				'Marcos Mallo-Leira',
				'Carmen Díez-Rivera',
				'Sahara Ugatz Mallo',
			],
			contact: 'marcosmallo@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Carmen Díez Rivera',
			leaderEmail: 'marcosmallo@gmail.com',
			name: 'Courel',
			otherName: null,
			year: '2021',
			months: 'Octubre-diciembre',
			province: 'Lugo',
			region: 'Galicia',
			coords: [42.6274929, -7.0982033],
			presence: true,
			partners: [
				'Marcos Mallo-Leira',
				'Carmen Díez-Rivera',
				'Sahara Ugatz Mallo',
			],
			contact: 'marcosmallo@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Carmen Díez Rivera',
			leaderEmail: 'marcosmallo@gmail.com',
			name: 'Enciña da Lastra',
			otherName: 'Enciña',
			year: '2022',
			months: 'Enero-marzo',
			province: 'Ourense',
			region: 'Galicia',
			coords: [42.4963164, -6.9231717],
			presence: true,
			partners: [
				'Marcos Mallo-Leira',
				'Carmen Díez-Rivera',
				'Sahara Ugatz Mallo',
			],
			contact: 'marcosmallo@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Marcos Mallo Leira',
			leaderEmail: 'marcosmallo@gmail.com',
			name: 'Negueira de Muñiz',
			otherName: 'Negueira',
			year: '2022',
			months: 'Marzo-junio',
			province: 'Lugo',
			region: 'Galicia',
			coords: [43.1178119, -6.9029234],
			presence: false,
			partners: [
				'Marcos Mallo-Leira',
				'Carmen Díez-Rivera',
				'Sahara Ugatz Mallo',
			],
			contact: 'marcosmallo@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Carmen Díez Rivera',
			leaderEmail: 'marcosmallo@gmail.com',
			name: 'Serra da Faladoira',
			otherName: 'Faladoira',
			year: '2022',
			months: 'Noviembre-enero',
			province: 'A Coruña',
			region: 'Galicia',
			coords: [43.5756915, -7.7940454],
			presence: true,
			partners: [
				'Marcos Mallo-Leira',
				'Carmen Díez-Rivera',
				'Sahara Ugatz Mallo',
			],
			contact: 'marcosmallo@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Marcos Mallo Leira',
			leaderEmail: 'marcosmallo@gmail.com',
			name: 'Pena Maseira',
			otherName: null,
			year: '2023',
			months: 'Febrero-abril',
			province: 'Ourense',
			region: 'Galicia',
			coords: [42.0009655, -7.0148003],
			presence: true,
			partners: [
				'Marcos Mallo-Leira',
				'Carmen Díez-Rivera',
				'Sahara Ugatz Mallo',
			],
			contact: 'marcosmallo@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Marcos Mallo Leira',
			leaderEmail: 'marcosmallo@gmail.com',
			name: 'Pena Trevinca',
			otherName: null,
			year: '2023',
			months: 'Junio-agosto',
			province: 'Ourense',
			region: 'Galicia',
			coords: [42.2221009, -6.9193412],
			presence: true,
			partners: [
				'Marcos Mallo-Leira',
				'Carmen Díez-Rivera',
				'Sahara Ugatz Mallo',
			],
			contact: 'marcosmallo@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Carmen Díez Rivera',
			leaderEmail: 'marcosmallo@gmail.com',
			name: 'Verín',
			otherName: null,
			year: '2024',
			months: 'Febrero-abril',
			province: 'Ourense',
			region: 'Galicia',
			coords: [41.8796159, -7.575091],
			presence: false,
			partners: [
				'Marcos Mallo-Leira',
				'Carmen Díez-Rivera',
				'Sahara Ugatz Mallo',
			],
			contact: 'marcosmallo@gmail.com',
			link: null,
			photos: null,
		},
		{
			leader: 'Helena Rambla Corral',
			leaderEmail: 'info@proyectomadretierra.es',
			name: 'Archidona',
			otherName: null,
			year: '2024',
			months: 'Febrero-Mayo',
			province: 'Málaga',
			region: 'Andalucia',
			coords: [37.17402, -4.265595],
			presence: false,
			partners: ['Helena Rambla Corral'],
			contact: 'info@proyectomadretierra.es',
			link: null,
			photos: null,
		},
		{
			leader: 'Mario Galileo Antón Enríquez',
			leaderEmail: 'mgantonenriquez@gmail.com',
			name: 'Sierra Norte Sevilla',
			otherName: 'Almadén de la Plata',
			year: '2025',
			months: 'Abril-Septiembre',
			province: 'Sevilla',
			region: 'Andalucía',
			coords: [232134.69, 4192889.79],
			presence: false,
			partners: [
				'Mario Galileo Antón',
				'Mara Torreblanca',
				'Luis David Guerrero',
				'Jesús Manuel Aragón Rey',
				'Diego Avilés Morillo',
				'Juan Sanz Isorna',
				'Santiago Nieto',
				'Orestes Ramos Álvarez',
				'Irene Martínez Sanz',
				'Pablo Galván Mateos',
				'Mª Ángeles García-Rosales',
				'Daniel Pérez Barrios',
				'Kora Fernández Durán.',
			],
			contact: 'mgantonenriquez@gmail.com',
			link: 'https://drive.google.com/open?id=1ppktwq-_TeCWYLTXdkThs-3Y32a7P6Ha, https://drive.google.com/open?id=1vFxgKgQi4TIcBPGI-VvMSrCr17y4K0GI, https://drive.google.com/open?id=1csUlLEALbjuOSVCmB_JT8Uu30-T6j0rF, https://drive.google.com/open?id=1eU6p3fEEXTjT0qTYcaR97i5r3KgrKEla, https://drive.google.com/open?id=1zJdCy0bYTGOXEuE29b028rJF9deW8Qol, https://drive.google.com/open?id=1GmOtlei4gYD6GqjL6CQcQMTuFfC-Fm9b, https://drive.google.com/open?id=1ezPO3XJ7OlEcnuCIzIVkQGRzVryEBeCw, https://drive.google.com/open?id=1O7w5g5E3nLYnmWy-Jv08WsecGzXNUXHF, https://drive.google.com/open?id=1QWMErZxHV9lVAhdsLGZEcTNnVl_Wy-9z, https://drive.google.com/open?id=1LZGG7bWH6KxNdtwua__MUmI1uI8j9NJ9',
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Villar del humo',
			otherName: null,
			year: null,
			months: null,
			province: 'Cuenca',
			region: 'Castilla-La Mancha',
			coords: [39.7796271552758, -1.55608382933262],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Pajares',
			otherName: null,
			year: null,
			months: null,
			province: 'Guadalajara',
			region: 'Castilla-La Mancha',
			coords: [40.7222837689675, -2.83377519698496],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Alto Tajo/Zaorejas',
			otherName: null,
			year: null,
			months: null,
			province: 'Guadalajara',
			region: 'Castilla-La Mancha',
			coords: [40.7265383042053, -2.34334810460769],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Vega del codorno',
			otherName: null,
			year: null,
			months: null,
			province: 'Cuenca',
			region: 'Castilla-La Mancha',
			coords: [40.4399208110591, -1.90662355784606],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Bogarra',
			otherName: null,
			year: null,
			months: null,
			province: 'Albacete',
			region: 'Castilla-La Mancha',
			coords: [38.5739410701654, -2.21586230012472],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'cuevas del sil',
			otherName: null,
			year: null,
			months: null,
			province: 'León',
			region: 'Castilla y León',
			coords: [42.9316099107068, -6.38783127413007],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'xistral',
			otherName: null,
			year: null,
			months: null,
			province: 'Lugo',
			region: 'Galicia',
			coords: [43.4872101593498, -7.59258696028292],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'albaladejo',
			otherName: null,
			year: null,
			months: null,
			province: 'Ciudad Real',
			region: 'Castilla-La Mancha',
			coords: [38.6756332053789, -2.82977671434113],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'arana',
			otherName: null,
			year: null,
			months: null,
			province: 'Granada',
			region: 'Andalucía',
			coords: [37.373581555535, -3.48142544277112],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'filabres',
			otherName: null,
			year: null,
			months: null,
			province: 'Almería',
			region: 'Andalucía',
			coords: [37.2989397433728, -2.5058719398057],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'giribaile',
			otherName: null,
			year: null,
			months: null,
			province: 'Jaén',
			region: 'Andalucía',
			coords: [38.0860704808486, -3.53320078351639],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'la cabezuela',
			otherName: null,
			year: null,
			months: null,
			province: 'Ciudad Real',
			region: 'Castilla-La Mancha',
			coords: [38.6740336724318, -3.19062466898532],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'muela de cortes',
			otherName: null,
			year: null,
			months: null,
			province: 'Valencia',
			region: 'Comunidad Valenciana',
			coords: [39.2080872706506, -0.95091075867714],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'murcia',
			otherName: null,
			year: null,
			months: null,
			province: 'Murcia',
			region: 'Región de Murcia',
			coords: [37.9104235437746, -1.39155919679097],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'petrola',
			otherName: null,
			year: null,
			months: null,
			province: 'Albacete',
			region: 'Castilla-La Mancha',
			coords: [38.8536097456975, -1.56428102530181],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'puerta alta',
			otherName: null,
			year: null,
			months: null,
			province: 'Granada',
			region: 'Andalucía',
			coords: [37.4811213666652, -3.75707195181381],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'requena',
			otherName: null,
			year: null,
			months: null,
			province: 'Valencia',
			region: 'Comunidad Valenciana',
			coords: [39.4364458927464, -1.23007073074276],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'santillana',
			otherName: null,
			year: null,
			months: null,
			province: 'Almería',
			region: 'Andalucía',
			coords: [37.0850489324338, -2.72719589549701],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'sierra altaona',
			otherName: null,
			year: null,
			months: null,
			province: 'Murcia',
			region: 'Región de Murcia',
			coords: [37.9608544152921, -1.01406514334483],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'sierra argue a',
			otherName: null,
			year: null,
			months: null,
			province: 'Alicante',
			region: 'Comunidad Valenciana',
			coords: [38.5868427265839, -0.740330641017345],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Sierra Alhamilla',
			otherName: null,
			year: null,
			months: null,
			province: 'Almería',
			region: 'Andalucía',
			coords: [36.9568563828329, -2.3284163414437],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'sierra gador',
			otherName: null,
			year: null,
			months: null,
			province: 'Almería',
			region: 'Andalucía',
			coords: [36.8431991737559, -2.7228980977282],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'villuercas',
			otherName: null,
			year: null,
			months: null,
			province: 'Cáceres',
			region: 'Extremadura',
			coords: [39.5094197852379, -5.35725367689058],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Segura',
			otherName: null,
			year: null,
			months: null,
			province: 'Jaén',
			region: 'Andalucía',
			coords: [38.2408477319534, -2.54963809083906],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'harana',
			otherName: null,
			year: null,
			months: null,
			province: 'Granada',
			region: 'Andalucía',
			coords: [37.373581555535, -3.48142544277112],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'alava',
			otherName: null,
			year: null,
			months: null,
			province: 'Álava',
			region: 'País Vasco',
			coords: [42.6912406921219, -2.59254274273626],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'almanza',
			otherName: null,
			year: null,
			months: null,
			province: 'León',
			region: 'Castilla y León',
			coords: [42.6598250301838, -5.05385640462124],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'atienza',
			otherName: null,
			year: null,
			months: null,
			province: 'Guadalajara',
			region: 'Castilla-La Mancha',
			coords: [41.1772044832946, -2.88606976294176],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'bo ar',
			otherName: null,
			year: null,
			months: null,
			province: 'León',
			region: 'Castilla y León',
			coords: [42.8663483449859, -5.34118181970578],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'ordesa',
			otherName: null,
			year: null,
			months: null,
			province: 'Huesca',
			region: 'Aragón',
			coords: [42.6555101273107, -0.0953141942162779],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'palacios de  la sierra',
			otherName: null,
			year: null,
			months: null,
			province: 'Burgos',
			region: 'Castilla y León',
			coords: [41.9825987272245, -3.08882162746827],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'quintos de  Mora',
			otherName: null,
			year: null,
			months: null,
			province: 'Toledo',
			region: 'Castilla-La Mancha',
			coords: [39.4193493964002, -4.0941536210899],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'robledillo',
			otherName: null,
			year: null,
			months: null,
			province: 'Madrid',
			region: 'Comunidad de Madrid',
			coords: [40.935890017948, -3.53488142477451],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'rozadio',
			otherName: null,
			year: null,
			months: null,
			province: 'Cantabria',
			region: 'Cantabria',
			coords: [43.2071835652414, -4.39560207955591],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Serranillos',
			otherName: null,
			year: null,
			months: null,
			province: 'Ávila',
			region: 'Castilla y León',
			coords: [40.3364868869475, -4.9024790648505],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'soba',
			otherName: null,
			year: null,
			months: null,
			province: 'Cantabria',
			region: 'Cantabria',
			coords: [43.1620108008443, -3.46052637477545],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'valdemoro',
			otherName: null,
			year: null,
			months: null,
			province: 'Cuenca',
			region: 'Castilla-La Mancha',
			coords: [40.1252594714132, -1.78190886433571],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'villagordo',
			otherName: null,
			year: null,
			months: null,
			province: 'Cuenca',
			region: 'Castilla-La Mancha',
			coords: [39.666485280696, -2.49348132377149],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Escuain',
			otherName: null,
			year: null,
			months: null,
			province: 'Huesca',
			region: 'Aragón',
			coords: [42.5721353734944, 0.139661863716487],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'a isclo',
			otherName: null,
			year: null,
			months: null,
			province: 'Huesca',
			region: 'Aragón',
			coords: [42.5324696452357, 0.090008539232081],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'girona',
			otherName: null,
			year: null,
			months: null,
			province: 'Girona',
			region: 'Cataluña',
			coords: [42.1227795714495, 2.54638562892321],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Finca_Finat_Segovia',
			otherName: null,
			year: null,
			months: null,
			province: 'Segovia',
			region: 'Castilla y León',
			coords: [40.6509190628702, -4.335291247915],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Aldeanueva de la Serrezuela',
			otherName: null,
			year: null,
			months: null,
			province: 'Segovia',
			region: 'Castilla y León',
			coords: [41.4654592567999, -3.78378655686914],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Ventosa del Pisuerga',
			otherName: null,
			year: null,
			months: null,
			province: 'Palencia',
			region: 'Castilla y León',
			coords: [42.5194469567583, -4.32729795870012],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Sierra de Gata',
			otherName: null,
			year: null,
			months: null,
			province: 'Salamanca',
			region: 'Castilla y León',
			coords: [40.2706932328615, -6.79064300320151],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Caba eros',
			otherName: null,
			year: null,
			months: null,
			province: 'Ciudad Real',
			region: 'Castilla-La Mancha',
			coords: [39.3607373400578, -4.46307361591826],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Lerida',
			otherName: null,
			year: null,
			months: null,
			province: 'Lleida',
			region: 'Cataluña',
			coords: [42.0619620106908, 0.738697077681498],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Bardenas',
			otherName: null,
			year: null,
			months: null,
			province: 'Zaragoza',
			region: 'Aragón',
			coords: [42.0488666891916, -1.28905665162394],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Zilbeti',
			otherName: null,
			year: null,
			months: null,
			province: 'Navarra',
			region: 'Comunidad Foral de Navarra',
			coords: [42.9590861891685, -1.47135563771719],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Zaragoza',
			otherName: null,
			year: null,
			months: null,
			province: 'Zaragoza',
			region: 'Aragón',
			coords: [41.5084417343885, -1.76551670322682],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Beceite',
			otherName: null,
			year: null,
			months: null,
			province: 'Teruel',
			region: 'Aragón',
			coords: [40.7641559455796, 0.18111377691429],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Zona Sara/Pablo',
			otherName: null,
			year: null,
			months: null,
			province: 'Guadalajara',
			region: 'Castilla-La Mancha',
			coords: [40.4408265984997, -2.79860459416263],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Lezuza',
			otherName: null,
			year: null,
			months: null,
			province: 'Albacete',
			region: 'Castilla-La Mancha',
			coords: [38.8990092815629, -2.33782025524155],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Destriana',
			otherName: null,
			year: null,
			months: null,
			province: 'León',
			region: 'Castilla y León',
			coords: [42.3164686538182, -6.10816736720188],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Gallegos de Solmiron',
			otherName: null,
			year: null,
			months: null,
			province: 'Ávila',
			region: 'Castilla y León',
			coords: [40.5260732531258, -5.43041014684117],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Diego del carpio',
			otherName: null,
			year: null,
			months: null,
			province: 'Ávila',
			region: 'Castilla y León',
			coords: [40.6504256170451, -5.34098052903256],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Ezcaray',
			otherName: null,
			year: null,
			months: null,
			province: 'La Rioja',
			region: 'La Rioja',
			coords: [42.3453662739184, -3.06418732063837],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Guara',
			otherName: null,
			year: null,
			months: null,
			province: 'Huesca',
			region: 'Aragón',
			coords: [42.3098672355332, -0.537535885076732],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Rascafria',
			otherName: null,
			year: null,
			months: null,
			province: 'Madrid',
			region: 'Comunidad de Madrid',
			coords: [40.8925539021441, -3.9154961310242],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Manzanares el real',
			otherName: null,
			year: null,
			months: null,
			province: 'Madrid',
			region: 'Comunidad de Madrid',
			coords: [40.7550859190733, -3.91216236933216],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Colmenar de Arroyo',
			otherName: null,
			year: null,
			months: null,
			province: 'Madrid',
			region: 'Comunidad de Madrid',
			coords: [40.4190196499409, -4.2246822084152],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Caudiel',
			otherName: null,
			year: null,
			months: null,
			province: 'Castellón',
			region: 'Comunidad Valenciana',
			coords: [39.9911309550458, -0.552934242698135],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Sª Escalona',
			otherName: null,
			year: null,
			months: null,
			province: 'Alicante',
			region: 'Comunidad Valenciana',
			coords: [37.9407266156341, -0.853243062819579],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Sª de Salinas',
			otherName: null,
			year: null,
			months: null,
			province: 'Alicante',
			region: 'Comunidad Valenciana',
			coords: [38.4929396399584, -0.97234340462172],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Vinuesa',
			otherName: null,
			year: null,
			months: null,
			province: 'Soria',
			region: 'Castilla y León',
			coords: [41.8610647397332, -2.53969768189366],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Valdegeña',
			otherName: null,
			year: null,
			months: null,
			province: 'Soria',
			region: 'Castilla y León',
			coords: [41.8365058534583, -2.14165577474291],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Paca',
			otherName: null,
			year: null,
			months: null,
			province: 'Murcia',
			region: 'Región de Murcia',
			coords: [37.8374915084645, -1.77458728929032],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Santa Coloma',
			otherName: null,
			year: null,
			months: null,
			province: 'La Rioja',
			region: 'La Rioja',
			coords: [42.3692329899231, -2.61725677482888],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Moratalla',
			otherName: null,
			year: null,
			months: null,
			province: 'Murcia',
			region: 'Región de Murcia',
			coords: [38.2317689220381, -1.78550313859765],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Valle de hecho',
			otherName: null,
			year: null,
			months: null,
			province: 'Huesca',
			region: 'Aragón',
			coords: [42.7312749614485, -0.728236890046773],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Río lobos',
			otherName: null,
			year: null,
			months: null,
			province: 'Soria',
			region: 'Castilla y León',
			coords: [41.6304969529439, -3.04592853754704],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Nuevo Baztán',
			otherName: null,
			year: null,
			months: null,
			province: 'Madrid',
			region: 'Comunidad de Madrid',
			coords: [40.3783304759123, -3.22887392005366],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'San Vicente de Robres',
			otherName: null,
			year: null,
			months: null,
			province: 'La Rioja',
			region: 'La Rioja',
			coords: [42.2775864794679, -2.26097133525825],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Aneto',
			otherName: null,
			year: null,
			months: null,
			province: 'Huesca',
			region: 'Aragón',
			coords: [42.6242469013414, 0.575404793891355],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'El Castañar',
			otherName: null,
			year: null,
			months: null,
			province: 'Toledo',
			region: 'Castilla-La Mancha',
			coords: [39.6766476629676, -4.07433267976939],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Nogueras',
			otherName: null,
			year: null,
			months: null,
			province: 'Teruel',
			region: 'Aragón',
			coords: [41.1042064157608, -1.09719325641444],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Tierrantona',
			otherName: null,
			year: null,
			months: null,
			province: 'Huesca',
			region: 'Aragón',
			coords: [42.3681415584045, 0.292828798404175],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Fonz',
			otherName: null,
			year: null,
			months: null,
			province: 'Huesca',
			region: 'Aragón',
			coords: [42.0558137575972, 0.292277106412973],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Zaorejas - Alto Tajo',
			otherName: null,
			year: null,
			months: null,
			province: 'Guadalajara',
			region: 'Castilla-La Mancha',
			coords: [40.7142838701062, -2.33406334949005],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Molina de Aragón',
			otherName: null,
			year: null,
			months: null,
			province: 'Guadalajara',
			region: 'Castilla-La Mancha',
			coords: [41.0492858820883, -1.83041033673908],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Mancha real',
			otherName: null,
			year: null,
			months: null,
			province: 'Jaén',
			region: 'Andalucía',
			coords: [37.7635748563848, -3.60751389677192],
			presence: false,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Castejón',
			otherName: null,
			year: null,
			months: null,
			province: 'Zaragoza',
			region: 'Aragón',
			coords: [41.9110694284908, -0.917133983031738],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Monsagro',
			otherName: null,
			year: null,
			months: null,
			province: 'Salamanca',
			region: 'Castilla y León',
			coords: [40.4790601599619, -6.33700782195497],
			presence: true,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Aznalcazar',
			otherName: null,
			year: null,
			months: null,
			province: 'Sevilla',
			region: 'Andalucía',
			coords: [37.2506928741826, -6.20641797138678],
			presence: false,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'rio frio',
			otherName: null,
			year: null,
			months: null,
			province: 'Ciudad Real',
			region: 'Castilla-La Mancha',
			coords: [39.0860053893431, -4.51074871634709],
			presence: false,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'sierra san pedro',
			otherName: null,
			year: null,
			months: null,
			province: 'Cáceres',
			region: 'Extremadura',
			coords: [39.4580835212559, -7.10962383580467],
			presence: false,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Embalse de Piedras',
			otherName: null,
			year: null,
			months: null,
			province: 'Huelva',
			region: 'Andalucía',
			coords: [37.3880527679365, -7.32948111013693],
			presence: false,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Aracena',
			otherName: null,
			year: null,
			months: null,
			province: 'Huelva',
			region: 'Andalucía',
			coords: [37.9198800496879, -6.25125136426858],
			presence: false,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Monfrague',
			otherName: null,
			year: null,
			months: null,
			province: 'Cáceres',
			region: 'Extremadura',
			coords: [39.8420842664228, -6.04132251621738],
			presence: false,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'culebra',
			otherName: null,
			year: null,
			months: null,
			province: 'Zamora',
			region: 'Castilla y León',
			coords: [41.9213591993985, -6.36107271251987],
			presence: false,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'almijara',
			otherName: null,
			year: null,
			months: null,
			province: 'Granada',
			region: 'Andalucía',
			coords: [36.8955098819324, -3.77441314795465],
			presence: false,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'campos de  calatrava',
			otherName: null,
			year: null,
			months: null,
			province: 'Ciudad Real',
			region: 'Castilla-La Mancha',
			coords: [38.7134538918228, -3.87818500837895],
			presence: false,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'chivatos',
			otherName: null,
			year: null,
			months: null,
			province: 'Córdoba',
			region: 'Andalucía',
			coords: [38.1005480308951, -5.54399145023786],
			presence: false,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'despe aperros',
			otherName: null,
			year: null,
			months: null,
			province: 'Jaén',
			region: 'Andalucía',
			coords: [38.4182967258834, -3.55995304969377],
			presence: false,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'magina',
			otherName: null,
			year: null,
			months: null,
			province: 'Jaén',
			region: 'Andalucía',
			coords: [37.7807083588914, -3.34300020038745],
			presence: false,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'manchita don benito',
			otherName: null,
			year: null,
			months: null,
			province: 'Badajoz',
			region: 'Extremadura',
			coords: [38.8156495117507, -5.92585586542907],
			presence: false,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'rio alias',
			otherName: null,
			year: null,
			months: null,
			province: 'Almería',
			region: 'Andalucía',
			coords: [37.0280298311632, -2.02082866151625],
			presence: false,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'ronda',
			otherName: null,
			year: null,
			months: null,
			province: 'Málaga',
			region: 'Andalucía',
			coords: [36.8749363533456, -5.10530464505559],
			presence: false,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'tabernas',
			otherName: null,
			year: null,
			months: null,
			province: 'Almería',
			region: 'Andalucía',
			coords: [37.0768257996394, -2.56121673790347],
			presence: false,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'valquemado',
			otherName: null,
			year: null,
			months: null,
			province: 'Jaén',
			region: 'Andalucía',
			coords: [38.2395233776215, -4.19566923742296],
			presence: false,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Guadalmellato',
			otherName: null,
			year: null,
			months: null,
			province: 'Córdoba',
			region: 'Andalucía',
			coords: [38.0011013372119, -4.59800595296254],
			presence: false,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'adamuz',
			otherName: null,
			year: null,
			months: null,
			province: 'Córdoba',
			region: 'Andalucía',
			coords: [38.0790100961183, -4.49175462710097],
			presence: false,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'tierra de pinares',
			otherName: null,
			year: null,
			months: null,
			province: 'Segovia',
			region: 'Castilla y León',
			coords: [41.367127734881, -4.32114778954733],
			presence: false,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'bosque de bonastre',
			otherName: null,
			year: null,
			months: null,
			province: 'Tarragona',
			region: 'Cataluña',
			coords: [41.2496499606734, 1.44501559361995],
			presence: false,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Zona Javi',
			otherName: null,
			year: null,
			months: null,
			province: 'Málaga',
			region: 'Andalucía',
			coords: [37.1707729429994, -4.83234418626835],
			presence: false,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Zarza-capilla',
			otherName: null,
			year: null,
			months: null,
			province: 'Badajoz',
			region: 'Extremadura',
			coords: [38.7571486983819, -5.1423869016789],
			presence: false,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Ricobayo',
			otherName: null,
			year: null,
			months: null,
			province: 'Zamora',
			region: 'Castilla y León',
			coords: [41.5702177606761, -6.00553456378618],
			presence: false,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Alpuente-losilla',
			otherName: null,
			year: null,
			months: null,
			province: 'Valencia',
			region: 'Comunidad Valenciana',
			coords: [39.9246786527242, -1.07025336161748],
			presence: false,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Este de Caspe',
			otherName: null,
			year: null,
			months: null,
			province: 'Zaragoza',
			region: 'Aragón',
			coords: [41.2218179894491, 0.0617548397008157],
			presence: false,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Valdelosa',
			otherName: null,
			year: null,
			months: null,
			province: 'Salamanca',
			region: 'Castilla y León',
			coords: [41.1885480784615, -5.79509365923387],
			presence: false,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Coves-Vilanova',
			otherName: null,
			year: null,
			months: null,
			province: 'Castellón',
			region: 'Comunidad Valenciana',
			coords: [40.2730408499361, 0.12787556215815],
			presence: false,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Losa-Chulilla',
			otherName: null,
			year: null,
			months: null,
			province: 'Valencia',
			region: 'Comunidad Valenciana',
			coords: [39.6842614235589, -0.878297845631554],
			presence: false,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Pico de la Cabrera',
			otherName: null,
			year: null,
			months: null,
			province: 'Córdoba',
			region: 'Andalucía',
			coords: [37.4446745229734, -4.36188656221767],
			presence: false,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Zona Oriol',
			otherName: null,
			year: null,
			months: null,
			province: 'Barcelona',
			region: 'Cataluña',
			coords: [41.2589697865561, 1.66431101280545],
			presence: false,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Parque sureste',
			otherName: null,
			year: null,
			months: null,
			province: 'Madrid',
			region: 'Comunidad de Madrid',
			coords: [40.2857124021262, -3.56021027342079],
			presence: false,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Oña',
			otherName: null,
			year: null,
			months: null,
			province: 'Burgos',
			region: 'Castilla y León',
			coords: [42.7446363056598, -3.40860297695307],
			presence: false,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Puerto Bajo',
			otherName: null,
			year: null,
			months: null,
			province: 'Jaén',
			region: 'Andalucía',
			coords: [38.2550556201855, -3.98828044569448],
			presence: false,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Cazorla',
			otherName: null,
			year: null,
			months: null,
			province: 'Jaén',
			region: 'Andalucía',
			coords: [37.8938803484327, -2.97565432974417],
			presence: false,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
		{
			leader: null,
			leaderEmail: null,
			name: 'Sobradillo-P.N. Arribes Duero-Águeda (SA)',
			otherName: null,
			year: null,
			months: null,
			province: 'Salamanca',
			region: 'Castilla y León',
			coords: [41.0127156856302, -6.78351564737037],
			presence: false,
			partners: [],
			contact: null,
			link: null,
			photos: null,
		},
	];
}
